

import { Course, CalendarEvent, GrantApplication, AssessmentCategory, ModeOfLearning, CourseType, LearnerProfile, TrainerProfile, Gender, EmploymentStatus, TrainerType, DeveloperProfile, AdminProfile, TrainingProviderProfile, Nationality, CourseSponsorship, Qualification, Education, WorkExperienceItem, JobPosting, Ethnicity, TpgStatus, TrainerStatus, LearnerProgress, DeveloperType, ClassStatus, PaymentMode, PaymentStatus } from './types';

const getFutureDate = (days: number) => {
    const date = new Date();
    date.setDate(date.getDate() + days);
    return date.toISOString().split('T')[0];
};

const getPastDate = (days: number) => {
    const date = new Date();
    date.setDate(date.getDate() - days);
    return date.toISOString().split('T')[0];
};

export const MOCK_COURSES: Course[] = [
  {
    id: 'react101',
    title: 'React for Beginners',
    learningOutcomes: 'A comprehensive introduction to the React library, covering hooks, components, and state management.',
    courseCode: 'TGS-2025053174',
    tscTitle: 'Web Development',
    tscCode: 'ICT-DIT-3011-1.1',
    tscKnowledge: "Knowledge of front-end development principles, JavaScript ES6 features, and component-based architecture.",
    tscAbilities: "Ability to create functional components, manage state with hooks (useState, useEffect), and handle user events.",
    courseRunId: '1133658',
    daId: 'RA415175',
    trainer: 'Jane Doe',
    trainingHours: 20,
    assessmentHours: 5,
    difficulty: 'Intermediate',
    modeOfLearning: [ModeOfLearning.Virtual],
    courseType: CourseType.WSQ,
    enrollmentStatus: 'enrolled',
    status: 'Published',
    courseFee: 499,
    taxPercent: 9,
    isWsqFunded: true,
    isSkillsFutureEligible: true,
    isPseaEligible: false,
    isMcesEligible: true,
    isIbfFunded: true,
    isUtapEligible: false,
    bookmarkedSubtopics: [],
    startDate: getPastDate(3), // Ongoing
    endDate: getFutureDate(2),
    classStatus: ClassStatus.Confirmed,
    paymentStatus: PaymentStatus.Paid,
    learnerGuideUrl: '/mock-data/react-for-beginners-guide.pdf',
    slidesUrl: '/mock-data/react-for-beginners-slides.pdf',
    lessonPlanUrl: '/mock-data/react-for-beginners-lesson-plan.pdf',
    assessmentPlanUrl: '/mock-data/react-for-beginners-assessment-plan.pdf',
    facilitatorGuideUrl: '/mock-data/react-for-beginners-facilitator-guide.pdf',
    trainerSlidesUrl: 'https://docs.google.com/presentation/d/example',
    isLeaderboardEnabled: true,
    certificateUrl: '/mock-data/certificates/react101-certificate.pdf',
    assessments: [
        { id: 'a1', title: 'Written Assessment', category: AssessmentCategory.WrittenExam, status: 'Published', questions: 'Answer all questions in the provided document.', fileUrl: '/mock-data/assessments/react101-written-exam.docx' },
        { id: 'a2', title: 'Practical Exam', category: AssessmentCategory.PracticalExam, status: 'Published', questions: 'Complete the practical tasks as described in the exam paper.', fileUrl: '/mock-data/assessments/react101-practical-exam.docx' },
    ],
    topics: [
      {
        id: 't1',
        title: 'Learning Unit 1: Introduction to React',
        subtopics: [
          { id: 'st1_1', title: 'What is JSX?', content: 'Learn the basics of JSX syntax, which allows you to write HTML-like code in JavaScript.' },
          { id: 'st1_2', title: 'Components and Props', content: 'Understand how to build and compose reusable components and pass data using props.' },
        ],
      },
      {
        id: 't2',
        title: 'Learning Unit 2: State and Lifecycle',
        subtopics: [
          { id: 'st2_1', title: 'Managing Component State', content: 'Learn how to use the `useState` hook to manage local component state effectively.' },
          { id: 'st2_2', title: 'Handling Events', content: 'Discover how to handle user events like clicks and form submissions in React.' },
        ],
      },
    ],
    learners: [
        { 
            name: 'Alice Johnson', 
            progressPercent: 75, 
            quizScore: 90, 
            tel: '91234567', 
            email: 'alice@example.com', 
            company: 'Tech Solutions', 
            paymentStatus: PaymentStatus.Paid, 
            assessmentGrades: [{assessmentId: 'a1', status: 'C'}, {assessmentId: 'a2', status: 'C'}], 
            submissions: [
                { assessmentId: 'a1', fileName: 'alice-johnson-react-written.pdf', submittedAt: getPastDate(1) + 'T10:30:00Z' },
            ], 
            grantId: 'GID-001A', 
            grantStatus: TpgStatus.Success, 
            claimStatus: TpgStatus.Success, 
            claimId: 'CID-001A',
            gender: Gender.Female, 
            dob: '1995-05-20', 
            courseSponsorship: CourseSponsorship.EmployerSponsored,
            paymentMode: PaymentMode.CompanySponsorship, 
            ethnicity: Ethnicity.Chinese,
            completedSubtopics: ['st1_1', 'st1_2', 'st2_1'],
            traineeId: 'S0118316H',
            enrolmentDate: '2020-05-15',
            sponsorshipType: 'EMPLOYER',
            nationality: Nationality.Singaporean,
            idType: { type: 'NRIC' },
            fees: {
                totalCourseFee: 499,
                grantAmount: 200,
                discount: 50.25,
                skillsFutureCreditClaim: 0,
                cashPayment: 293.66,
                invoiceNumber: 'INV-2024-0001',
                receiptNumber: 'REC-2024-0001',
            },
            bundle: {
                code: 'SSG-BC-2312-000001'
            },
            employer: {
                uen: 'G01234567S',
                contact: {
                    fullName: 'Stephen Chua',
                    emailAddress: 'stephen.chua@techsolutions.com',
                    contactNumber: {
                        areaCode: '00',
                        countryCode: '65',
                        phoneNumber: '88881234'
                    }
                }
            },
            contactNumber: {
                areaCode: "00",
                countryCode: "65",
                phoneNumber: '91234567'
            },
            centralProvidentFund: {
                traineeCategory: 'Secondee from Financial Institution (FI)',
                letterOfSupportIssuanceDate: '2014-12-31',
                didTraineeReceiveCPFContribution: 'Yes',
                isTraineeEmployedAtTimeofEnrolment: 'Yes'
            },
            trainingPartner: {
              uen: 'T16GB0003C',
              code: 'T16GB0003C-01'
            }
        },
        { name: 'Bob Williams', progressPercent: 40, quizScore: 55, tel: '98765432', email: 'bob@example.com', company: 'Innovate Inc.', paymentStatus: PaymentStatus.Paid, assessmentGrades: [{assessmentId: 'a1', status: 'C'}, {assessmentId: 'a2', status: 'C'}], submissions: [], grantId: 'GID-001B', grantStatus: TpgStatus.Success, claimStatus: TpgStatus.Success, claimId: 'CID-001B', gender: Gender.Male, dob: '1998-11-10', courseSponsorship: CourseSponsorship.SelfSponsored, paymentMode: PaymentMode.SkillsFutureCredit, ethnicity: Ethnicity.Malay, nationality: Nationality.SingaporePR, fees: { totalCourseFee: 499, grantAmount: 150, discount: 0, skillsFutureCreditClaim: 300, cashPayment: 93.91, invoiceNumber: 'INV-2024-0002', receiptNumber: 'REC-2024-0002' } },
        { name: 'Charlie Brown', progressPercent: 75, quizScore: 80, tel: '81239876', email: 'charlie@example.com', company: 'Web Weavers', paymentStatus: PaymentStatus.Unpaid, assessmentGrades: [{assessmentId: 'a1', status: 'C'}, {assessmentId: 'a2', status: 'C'}], 
            submissions: [
                 { assessmentId: 'a1', fileName: 'charlie-brown-react-written.pdf', submittedAt: getPastDate(1) + 'T11:00:00Z' }
            ], 
            grantId: 'GID-001C', grantStatus: TpgStatus.Success, claimStatus: TpgStatus.Success, claimId: 'CID-001C', gender: Gender.Male, dob: '1982-03-15', courseSponsorship: CourseSponsorship.EmployerSponsored, paymentMode: PaymentMode.CompanySponsorship, ethnicity: Ethnicity.Indian, nationality: Nationality.NonCitizen, fees: { totalCourseFee: 499, grantAmount: 200, discount: 0, skillsFutureCreditClaim: 0, cashPayment: 0, invoiceNumber: 'INV-2024-0003', receiptNumber: 'N/A' } },
        { name: 'Diana Miller', progressPercent: 100, quizScore: 95, tel: '87651234', email: 'diana@example.com', company: 'Data Dynamics', paymentStatus: PaymentStatus.Paid, assessmentGrades: [{assessmentId: 'a1', status: 'C'}, {assessmentId: 'a2', status: 'C'}], submissions: [], grantId: 'GID-001D', grantStatus: TpgStatus.Success, claimStatus: TpgStatus.Success, claimId: 'CID-001D', gender: Gender.Female, dob: '1979-07-22', courseSponsorship: CourseSponsorship.SelfSponsored, paymentMode: PaymentMode.Cash, ethnicity: Ethnicity.Others, nationality: Nationality.Singaporean, fees: { totalCourseFee: 499, grantAmount: 0, discount: 0, skillsFutureCreditClaim: 0, cashPayment: 543.91, invoiceNumber: 'INV-2024-0004', receiptNumber: 'REC-2024-0004' } },
    ],
  },
  {
    id: 'ts201',
    title: 'Advanced TypeScript',
    learningOutcomes: 'Dive deep into advanced TypeScript features like generics, decorators, and mapped types.',
    courseCode: 'TGS-2024012345',
    tscTitle: 'Advanced Programming',
    tscCode: 'ICT-DIT-4012-2.1',
    tscKnowledge: "Deep understanding of TypeScript's type system, including generics, interfaces, and type inference.",
    tscAbilities: "Ability to apply advanced types to build scalable and maintainable applications, and configure TypeScript projects.",
    courseRunId: '1133661',
    daId: 'RA415176',
    trainer: 'John Smith',
    trainingHours: 14,
    assessmentHours: 4,
    difficulty: 'Beginner-Intermediate',
    modeOfLearning: [ModeOfLearning.Physical],
    courseType: CourseType.IBF,
    enrollmentStatus: 'not-enrolled',
    status: 'Published',
    courseFee: 650,
    taxPercent: 9,
    isWsqFunded: true,
    isSkillsFutureEligible: true,
    isPseaEligible: true,
    isMcesEligible: true,
    isIbfFunded: false,
    isUtapEligible: true,
    bookmarkedSubtopics: [],
    startDate: getFutureDate(25), // Upcoming
    endDate: getFutureDate(27),
    classStatus: ClassStatus.Pending,
    paymentStatus: PaymentStatus.Pending,
    learnerGuideUrl: '/mock-data/advanced-typescript-guide.pdf',
    slidesUrl: '/mock-data/advanced-typescript-slides.pdf',
    lessonPlanUrl: '/mock-data/advanced-typescript-lesson-plan.pdf',
    assessmentPlanUrl: '/mock-data/advanced-typescript-assessment-plan.pdf',
    facilitatorGuideUrl: '/mock-data/advanced-typescript-facilitator-guide.pdf',
    trainerSlidesUrl: '/mock-data/advanced-typescript-trainer-slides.ppt',
    isLeaderboardEnabled: false,
    assessments: [
        { id: 'a3_1', title: 'Written Assessment', category: AssessmentCategory.WrittenExam, status: 'Draft', questions: 'Answer all questions in the provided document.' },
        { id: 'a3', title: 'Generics Practical Exam', category: AssessmentCategory.PracticalExam, status: 'Draft', questions: 'Create a reusable TypeScript function that uses generics to sort an array of any object type by a given key.' },
    ],
    topics: [
        {
            id: 't3',
            title: 'Learning Unit 1: Advanced Types',
            subtopics: [
              { id: 'st3_1', title: 'Generics', content: 'Create reusable, type-safe components and functions with generics.' },
              { id: 'st3_2', title: 'Utility Types', content: 'Leverage built-in utility types to write cleaner and more maintainable code.' },
            ],
        },
        {
            id: 't3_2',
            title: 'Learning Unit 2: Decorators and Metadata',
            subtopics: [
              { id: 'st3_3', title: 'Class Decorators', content: 'Content about class decorators.' },
              { id: 'st3_4', title: 'Method Decorators', content: 'Content about method decorators.' },
            ],
        },
        {
            id: 't3_3',
            title: 'Learning Unit 3: Namespaces and Modules',
            subtopics: [
              { id: 'st3_5', title: 'Using Namespaces', content: 'Content about using namespaces.' },
              { id: 'st3_6', title: 'ES Modules', content: 'Content about ES Modules.' },
            ],
        }
    ],
    learners: [
        { name: 'Eve Davis', progressPercent: 80, quizScore: 85, tel: '93456789', email: 'eve@example.com', company: 'Code Crafters', paymentStatus: PaymentStatus.Paid, assessmentGrades: [{assessmentId: 'a3', status: 'C'}], submissions: [], grantId: 'GID-002A', grantStatus: TpgStatus.Success, claimStatus: TpgStatus.Success, claimId: 'CID-002A', gender: Gender.Female, dob: '1996-01-30', courseSponsorship: CourseSponsorship.SelfSponsored, paymentMode: PaymentMode.SkillsFutureCredit, ethnicity: Ethnicity.Chinese, nationality: Nationality.SingaporePR, fees: { totalCourseFee: 650, grantAmount: 300, discount: 0, skillsFutureCreditClaim: 350, cashPayment: 58.5, invoiceNumber: 'INV-2024-0005', receiptNumber: 'REC-2024-0005' } },
        { name: 'Frank White', progressPercent: 25, quizScore: null, tel: '94567890', email: 'frank@example.com', company: 'Pixel Perfect', paymentStatus: PaymentStatus.Unpaid, assessmentGrades: [{assessmentId: 'a3', status: 'NYC'}], submissions: [], grantId: 'GID-002B', grantStatus: TpgStatus.Pending, claimStatus: TpgStatus.Pending, claimId: 'CID-002B', gender: Gender.Male, dob: '1975-09-05', courseSponsorship: CourseSponsorship.EmployerSponsored, paymentMode: PaymentMode.CompanySponsorship, ethnicity: Ethnicity.Malay, nationality: Nationality.Singaporean, fees: { totalCourseFee: 650, grantAmount: 400, discount: 50, skillsFutureCreditClaim: 0, cashPayment: 0, invoiceNumber: 'INV-2024-0006', receiptNumber: 'N/A' } },
        { name: 'Grace Lee', progressPercent: 50, quizScore: 60, tel: '95678901', email: 'grace@example.com', company: 'Tech Solutions', paymentStatus: PaymentStatus.Paid, assessmentGrades: [{assessmentId: 'a3', status: 'Pending'}], submissions: [], grantId: null, grantStatus: TpgStatus.NA, claimStatus: TpgStatus.Failed, claimId: null, gender: Gender.Female, dob: '2000-02-18', courseSponsorship: CourseSponsorship.NA, paymentMode: PaymentMode.Cash, ethnicity: Ethnicity.Chinese, nationality: Nationality.NonCitizen, fees: { totalCourseFee: 650, grantAmount: 0, discount: 0, skillsFutureCreditClaim: 0, cashPayment: 708.5, invoiceNumber: 'INV-2024-0007', receiptNumber: 'REC-2024-0007' } },
    ],
  },
  {
    id: 'ai301',
    title: 'Generative AI Fundamentals',
    learningOutcomes: 'Explore the world of generative AI models and learn how to integrate them into your applications.',
    courseCode: 'TGS-2024067890',
    tscTitle: 'Artificial Intelligence',
    tscCode: 'ICT-AIE-5001-1.1',
    tscKnowledge: "Knowledge of large language models (LLMs), prompt engineering techniques, and API integration principles.",
    tscAbilities: "Ability to interact with generative AI models via APIs, craft effective prompts, and parse model responses.",
    courseRunId: '1133662',
    daId: 'RA415177',
    trainer: 'Alex Ray',
    trainingHours: 32,
    assessmentHours: 8,
    difficulty: 'Intermediate-Advanced',
    modeOfLearning: [ModeOfLearning.Virtual],
    courseType: CourseType.NonWSQ,
    enrollmentStatus: 'enrolled',
    status: 'Draft',
    courseFee: 899,
    taxPercent: 9,
    isWsqFunded: false,
    isSkillsFutureEligible: true,
    isPseaEligible: false,
    isMcesEligible: false,
    isIbfFunded: true,
    isUtapEligible: true,
    bookmarkedSubtopics: [],
    startDate: getFutureDate(40), // Upcoming
    endDate: getFutureDate(44),
    classStatus: ClassStatus.Pending,
    paymentStatus: PaymentStatus.Overdue,
    learnerGuideUrl: '/mock-data/gen-ai-guide.pdf',
    slidesUrl: '/mock-data/gen-ai-slides.pdf',
    lessonPlanUrl: '/mock-data/gen-ai-lesson-plan.pdf',
    assessmentPlanUrl: '/mock-data/gen-ai-assessment-plan.pdf',
    facilitatorGuideUrl: '/mock-data/gen-ai-facilitator-guide.pdf',
    trainerSlidesUrl: 'https://docs.google.com/presentation/d/example2',
    isLeaderboardEnabled: true,
    assessments: [
        { id: 'a4', title: 'Written Assessment', category: AssessmentCategory.WrittenExam, status: 'Draft', questions: 'Write a series of prompts to guide an AI model to generate a short story in the style of a famous author.' },
        { id: 'a5', title: 'Case Study', category: AssessmentCategory.Project, status: 'Draft', questions: 'Demonstrate a working application that integrates with the Gemini API to perform a specific task.' },
    ],
    topics: [
        {
            id: 't4',
            title: 'Learning Unit 1: Introduction to LLMs',
            subtopics: [
                { id: 'st4_1', title: 'Understanding LLMs', content: 'Understand the core architecture and principles of large language models.' },
                { id: 'st4_2', title: 'Prompt Engineering', content: 'Learn the art and science of crafting effective prompts to get the desired outputs from AI models.' },
            ],
        },
        {
            id: 't5',
            title: 'Learning Unit 2: Building with the Gemini API',
            subtopics: [
                { id: 'st5_1', title: 'Getting Started with Gemini', content: 'A hands-on guide to setting up and making your first call to the Gemini API.' },
            ],
        },
    ],
    learners: [
        { name: 'Alice Johnson', progressPercent: 100, quizScore: 100, tel: '91234567', email: 'alice@example.com', company: 'Tech Solutions', paymentStatus: PaymentStatus.Paid, assessmentGrades: [{assessmentId: 'a4', status: 'C'}, {assessmentId: 'a5', status: 'C'}], submissions: [], grantId: null, grantStatus: TpgStatus.NA, claimStatus: TpgStatus.Success, claimId: 'CID-003A', gender: Gender.Female, dob: '1995-05-20', courseSponsorship: CourseSponsorship.EmployerSponsored, paymentMode: PaymentMode.CompanySponsorship, ethnicity: Ethnicity.Chinese, completedSubtopics: ['st4_1', 'st4_2', 'st5_1'], nationality: Nationality.Singaporean, fees: { totalCourseFee: 899, grantAmount: 0, discount: 0, skillsFutureCreditClaim: 0, cashPayment: 980, invoiceNumber: 'INV-2024-0008', receiptNumber: 'REC-2024-0008' } },
        { name: 'Heidi Garcia', progressPercent: 100, quizScore: 100, tel: '96789012', email: 'heidi@example.com', company: 'Innovate Inc.', paymentStatus: PaymentStatus.Paid, assessmentGrades: [{assessmentId: 'a4', status: 'C'}, {assessmentId: 'a5', status: 'C'}], submissions: [], grantId: null, grantStatus: TpgStatus.NA, claimStatus: TpgStatus.Success, claimId: 'CID-003B', gender: Gender.Female, dob: '1993-06-25', courseSponsorship: CourseSponsorship.SelfSponsored, paymentMode: PaymentMode.SkillsFutureCredit, ethnicity: Ethnicity.Others, nationality: Nationality.NonCitizen, fees: { totalCourseFee: 899, grantAmount: 0, discount: 100, skillsFutureCreditClaim: 500, cashPayment: 371.11, invoiceNumber: 'INV-2024-0009', receiptNumber: 'REC-2024-0009' } },
        { name: 'Ivan Rodriguez', progressPercent: 90, quizScore: 88, tel: '97890123', email: 'ivan@example.com', company: 'Web Weavers', paymentStatus: PaymentStatus.Unpaid, assessmentGrades: [{assessmentId: 'a4', status: 'Pending'}, {assessmentId: 'a5', status: 'Pending'}], submissions: [], grantId: 'GID-003A', grantStatus: TpgStatus.Pending, claimStatus: TpgStatus.Pending, claimId: 'CID-003C', gender: Gender.Male, dob: '1980-12-01', courseSponsorship: CourseSponsorship.EmployerSponsored, paymentMode: PaymentMode.CompanySponsorship, ethnicity: Ethnicity.Indian, nationality: Nationality.SingaporePR, fees: { totalCourseFee: 899, grantAmount: 400, discount: 0, skillsFutureCreditClaim: 0, cashPayment: 0, invoiceNumber: 'INV-2024-0010', receiptNumber: 'N/A' } },
    ],
  },
  {
    id: 'py401',
    title: 'Python for Data Science',
    learningOutcomes: 'Master Python for data analysis with libraries like Pandas, NumPy, and Matplotlib.',
    courseCode: 'TGS-2024081123',
    tscTitle: 'Data Analysis',
    tscCode: 'ICT-DIT-4022-1.1',
    tscKnowledge: "Knowledge of Python programming fundamentals and data structures.",
    tscAbilities: "Ability to manipulate data with Pandas DataFrames and create visualizations.",
    courseRunId: '1133659',
    daId: 'RA415178',
    trainer: 'John Smith',
    trainingHours: 24,
    assessmentHours: 6,
    difficulty: 'Intermediate',
    modeOfLearning: [ModeOfLearning.Hybrid],
    courseType: CourseType.IBF,
    enrollmentStatus: 'enrolled',
    status: 'Published',
    courseFee: 799,
    taxPercent: 9,
    isWsqFunded: true,
    isSkillsFutureEligible: true,
    isPseaEligible: false,
    isMcesEligible: true,
    isIbfFunded: true,
    isUtapEligible: false,
    bookmarkedSubtopics: [],
    startDate: getPastDate(2), // Started 2 days ago
    endDate: getFutureDate(3), // Ends in 3 days
    classStatus: ClassStatus.Confirmed,
    paymentStatus: PaymentStatus.Paid,
    learnerGuideUrl: '/mock-data/python-ds-guide.pdf',
    slidesUrl: '/mock-data/python-ds-slides.pdf',
    lessonPlanUrl: '/mock-data/python-ds-lesson-plan.pdf',
    assessmentPlanUrl: '/mock-data/python-ds-assessment-plan.pdf',
    facilitatorGuideUrl: '/mock-data/python-ds-facilitator-guide.pdf',
    trainerSlidesUrl: '/mock-data/python-ds-trainer-slides.ppt',
    isLeaderboardEnabled: true,
    assessments: [
        { id: 'a6_1', title: 'Written Assessment', category: AssessmentCategory.WrittenExam, status: 'Published', accessCode: '987655' },
        { id: 'a6', title: 'Data Cleaning Project', category: AssessmentCategory.Project, status: 'Published', accessCode: '987654' },
    ],
    topics: [],
    learners: [
        { name: 'Grace Lee', progressPercent: 50, quizScore: 60, tel: '95678901', email: 'grace@example.com', company: 'Tech Solutions', paymentStatus: PaymentStatus.Paid, assessmentGrades: [{assessmentId: 'a6', status: 'Pending'}], 
            submissions: [
                { assessmentId: 'a6', fileName: 'grace-lee-python-project.zip', submittedAt: getPastDate(0) + 'T18:00:00Z'}
            ],
            grantId: null, grantStatus: TpgStatus.NA, claimStatus: TpgStatus.Failed, claimId: null, gender: Gender.Female, dob: '2000-02-18', courseSponsorship: CourseSponsorship.NA, paymentMode: PaymentMode.Cash, ethnicity: Ethnicity.Chinese, nationality: Nationality.NonCitizen, fees: { totalCourseFee: 799, grantAmount: 0, discount: 0, skillsFutureCreditClaim: 0, cashPayment: 870.91, invoiceNumber: 'INV-2024-0011', receiptNumber: 'REC-2024-0011' } },
        { name: 'Diana Miller', progressPercent: 45, quizScore: null, tel: '87651234', email: 'diana@example.com', company: 'Data Dynamics', paymentStatus: PaymentStatus.Paid, assessmentGrades: [{assessmentId: 'a6', status: 'Pending'}], submissions: [], grantId: 'GID-001D', grantStatus: TpgStatus.Success, claimStatus: TpgStatus.Pending, claimId: 'CID-004A', gender: Gender.Female, dob: '1979-07-22', courseSponsorship: CourseSponsorship.SelfSponsored, paymentMode: PaymentMode.Cash, ethnicity: Ethnicity.Others, nationality: Nationality.Singaporean, fees: { totalCourseFee: 799, grantAmount: 300, discount: 0, skillsFutureCreditClaim: 0, cashPayment: 570.91, invoiceNumber: 'INV-2024-0012', receiptNumber: 'REC-2024-0012' } },
    ],
  },
  {
    id: 'agile501',
    title: 'Agile Project Management',
    learningOutcomes: 'Learn Agile and Scrum methodologies for effective project management.',
    courseCode: 'TGS-2024070145',
    tscTitle: 'Project Management',
    tscCode: 'ICT-PMT-4001-1.1',
    tscKnowledge: "Knowledge of project lifecycles and Agile principles.",
    tscAbilities: "Ability to facilitate Scrum events and manage a product backlog.",
    courseRunId: '1133660',
    daId: 'RA415179',
    trainer: 'Jane Doe',
    trainingHours: 14,
    assessmentHours: 2,
    difficulty: 'Beginner',
    modeOfLearning: [ModeOfLearning.Physical],
    courseType: CourseType.WSQ,
    enrollmentStatus: 'enrolled',
    status: 'Published',
    courseFee: 350,
    taxPercent: 9,
    isWsqFunded: true,
    isSkillsFutureEligible: true,
    isPseaEligible: true,
    isMcesEligible: true,
    isIbfFunded: false,
    isUtapEligible: true,
    bookmarkedSubtopics: [],
    startDate: getPastDate(10), // Started 10 days ago
    endDate: getPastDate(7),   // Ended 7 days ago
    classStatus: ClassStatus.Confirmed,
    paymentStatus: PaymentStatus.Paid,
    learnerGuideUrl: '/mock-data/agile-pm-guide.pdf',
    slidesUrl: '/mock-data/agile-pm-slides.pdf',
    lessonPlanUrl: '/mock-data/agile-pm-lesson-plan.pdf',
    assessmentPlanUrl: '/mock-data/agile-pm-assessment-plan.pdf',
    facilitatorGuideUrl: '/mock-data/agile-pm-facilitator-guide.pdf',
    trainerSlidesUrl: '/mock-data/agile-pm-trainer-slides.ppt',
    isLeaderboardEnabled: false,
    assessments: [
        { id: 'a7', title: 'Written Assessment', category: AssessmentCategory.WrittenExam, status: 'Published', accessCode: '123123' },
        { id: 'a8', title: 'Case Study', category: AssessmentCategory.Project, status: 'Published', accessCode: '123124' }
    ],
    topics: [],
    learners: [
        { name: 'Bob Williams', progressPercent: 100, quizScore: 95, tel: '98765432', email: 'bob@example.com', company: 'Innovate Inc.', paymentStatus: PaymentStatus.Paid, assessmentGrades: [{assessmentId: 'a7', status: 'C'}], submissions: [], grantId: 'GID-001B', grantStatus: TpgStatus.Success, claimStatus: TpgStatus.Success, claimId: 'CID-005A', gender: Gender.Male, dob: '1998-11-10', courseSponsorship: CourseSponsorship.SelfSponsored, paymentMode: PaymentMode.SkillsFutureCredit, ethnicity: Ethnicity.Malay, nationality: Nationality.SingaporePR, fees: { totalCourseFee: 350, grantAmount: 100, discount: 0, skillsFutureCreditClaim: 250, cashPayment: 31.5, invoiceNumber: 'INV-2024-0013', receiptNumber: 'REC-2024-0013' } },
    ],
  },
   // --- ADDED 4 COMPLETED COURSES FOR DEMO ---
  {
    id: 'ux202',
    title: 'Intro to UX Design',
    learningOutcomes: 'Understand the fundamentals of User Experience design and user research.',
    courseCode: 'TGS-2024030111',
    tscTitle: 'User Experience Design',
    tscCode: 'ICT-DIT-3021-1.1',
    tscKnowledge: "Knowledge of UX principles and research methods.",
    tscAbilities: "Ability to create user personas and wireframes.",
    courseRunId: '1133670',
    trainer: 'Jane Doe',
    trainingHours: 18,
    assessmentHours: 6,
    difficulty: 'Beginner',
    modeOfLearning: [ModeOfLearning.Virtual],
    courseType: CourseType.WSQ,
    enrollmentStatus: 'not-enrolled',
    status: 'Published',
    courseFee: 450,
    taxPercent: 9,
    isWsqFunded: true,
    isSkillsFutureEligible: true,
    isPseaEligible: true,
    isMcesEligible: true,
    isIbfFunded: false,
    isUtapEligible: false,
    startDate: getPastDate(30),
    endDate: getPastDate(25),
    classStatus: ClassStatus.Confirmed,
    paymentStatus: PaymentStatus.Paid,
    assessments: [
      { id: 'a9', title: 'Written Assessment', category: AssessmentCategory.WrittenExam, status: 'Published' },
    ],
    topics: [],
    learners: [
      { name: 'Eve Davis', progressPercent: 100, quizScore: 92, tel: '93456789', email: 'eve@example.com', company: 'Code Crafters', paymentStatus: PaymentStatus.Paid, assessmentGrades: [{assessmentId: 'a9', status: 'C'}], submissions: [], grantId: 'GID-005A', grantStatus: TpgStatus.Success, claimStatus: TpgStatus.Success, claimId: 'CID-006A', gender: Gender.Female, dob: '1996-01-30', courseSponsorship: CourseSponsorship.SelfSponsored, paymentMode: PaymentMode.SkillsFutureCredit, ethnicity: Ethnicity.Chinese, nationality: Nationality.SingaporePR, fees: { totalCourseFee: 450, grantAmount: 200, discount: 0, skillsFutureCreditClaim: 250, cashPayment: 40.5, invoiceNumber: 'INV-2024-0014', receiptNumber: 'REC-2024-0014' } },
    ],
  },
  {
    id: 'cloud303',
    title: 'Cloud Computing Essentials',
    learningOutcomes: 'Learn the core concepts of cloud computing, including models like IaaS, PaaS, and SaaS.',
    courseCode: 'TGS-2024040222',
    tscTitle: 'Cloud Management',
    tscCode: 'ICT-CLD-4001-1.1',
    tscKnowledge: "Understanding of cloud service models and deployment strategies.",
    tscAbilities: "Ability to compare major cloud providers and their core services.",
    courseRunId: '1133671',
    trainer: 'John Smith',
    trainingHours: 20,
    assessmentHours: 4,
    difficulty: 'Intermediate',
    modeOfLearning: [ModeOfLearning.Physical],
    courseType: CourseType.IBF,
    enrollmentStatus: 'not-enrolled',
    status: 'Published',
    courseFee: 550,
    taxPercent: 9,
    isWsqFunded: true,
    isSkillsFutureEligible: true,
    isPseaEligible: false,
    isMcesEligible: true,
    isIbfFunded: true,
    isUtapEligible: true,
    startDate: getPastDate(45),
    endDate: getPastDate(40),
    classStatus: ClassStatus.Confirmed,
    paymentStatus: PaymentStatus.Paid,
    assessments: [
      { id: 'a10', title: 'Case Study', category: AssessmentCategory.Project, status: 'Published' },
    ],
    topics: [],
    learners: [
      { name: 'Frank White', progressPercent: 100, quizScore: 88, tel: '94567890', email: 'frank@example.com', company: 'Pixel Perfect', paymentStatus: PaymentStatus.Paid, assessmentGrades: [{assessmentId: 'a10', status: 'C'}], submissions: [], grantId: 'GID-006A', grantStatus: TpgStatus.Success, claimStatus: TpgStatus.Success, claimId: 'CID-007A', gender: Gender.Male, dob: '1975-09-05', courseSponsorship: CourseSponsorship.EmployerSponsored, paymentMode: PaymentMode.CompanySponsorship, ethnicity: Ethnicity.Malay, nationality: Nationality.Singaporean, fees: { totalCourseFee: 550, grantAmount: 250, discount: 0, skillsFutureCreditClaim: 0, cashPayment: 349.5, invoiceNumber: 'INV-2024-0015', receiptNumber: 'REC-2024-0015' } },
      { name: 'Grace Lee', progressPercent: 100, quizScore: 95, tel: '95678901', email: 'grace@example.com', company: 'Tech Solutions', paymentStatus: PaymentStatus.Paid, assessmentGrades: [{assessmentId: 'a10', status: 'C'}], submissions: [], grantId: 'GID-006B', grantStatus: TpgStatus.Success, claimStatus: TpgStatus.Success, claimId: 'CID-007B', gender: Gender.Female, dob: '2000-02-18', courseSponsorship: CourseSponsorship.NA, paymentMode: PaymentMode.Cash, ethnicity: Ethnicity.Chinese, nationality: Nationality.NonCitizen, fees: { totalCourseFee: 550, grantAmount: 0, discount: 0, skillsFutureCreditClaim: 0, cashPayment: 599.5, invoiceNumber: 'INV-2024-0016', receiptNumber: 'REC-2024-0016' } },
    ],
  },
  {
    id: 'cyber101',
    title: 'Cyber Security Basics',
    learningOutcomes: 'An introduction to cybersecurity principles, common threats, and protective measures.',
    courseCode: 'TGS-2024050333',
    tscTitle: 'Cybersecurity',
    tscCode: 'ICT-CYS-3001-1.1',
    tscKnowledge: "Knowledge of common cyber threats and security best practices.",
    tscAbilities: "Ability to identify phishing attempts and secure personal data.",
    courseRunId: '1133672',
    trainer: 'Alex Ray',
    trainingHours: 16,
    assessmentHours: 4,
    difficulty: 'Beginner',
    modeOfLearning: [ModeOfLearning.Hybrid],
    courseType: CourseType.NonWSQ,
    enrollmentStatus: 'not-enrolled',
    status: 'Published',
    courseFee: 600,
    taxPercent: 9,
    isWsqFunded: false,
    isSkillsFutureEligible: true,
    isPseaEligible: true,
    isMcesEligible: true,
    isIbfFunded: true,
    isUtapEligible: true,
    startDate: getPastDate(60),
    endDate: getPastDate(55),
    classStatus: ClassStatus.Confirmed,
    paymentStatus: PaymentStatus.Paid,
    assessments: [
      { id: 'a11', title: 'Written Assessment', category: AssessmentCategory.WrittenExam, status: 'Published' },
    ],
    topics: [],
    learners: [
      { name: 'Heidi Garcia', progressPercent: 100, quizScore: 100, tel: '96789012', email: 'heidi@example.com', company: 'Innovate Inc.', paymentStatus: PaymentStatus.Paid, assessmentGrades: [{assessmentId: 'a11', status: 'C'}], submissions: [], grantId: 'GID-007A', grantStatus: TpgStatus.Success, claimStatus: TpgStatus.Success, claimId: 'CID-008A', gender: Gender.Female, dob: '1993-06-25', courseSponsorship: CourseSponsorship.SelfSponsored, paymentMode: PaymentMode.SkillsFutureCredit, ethnicity: Ethnicity.Others, nationality: Nationality.NonCitizen, fees: { totalCourseFee: 600, grantAmount: 0, discount: 0, skillsFutureCreditClaim: 500, cashPayment: 154, invoiceNumber: 'INV-2024-0017', receiptNumber: 'REC-2024-0017' } },
    ],
  },
  {
    id: 'devops201',
    title: 'DevOps Fundamentals',
    learningOutcomes: 'Learn about DevOps culture, tools, and practices like CI/CD.',
    courseCode: 'TGS-2024060444',
    tscTitle: 'DevOps',
    tscCode: 'ICT-DVO-4001-1.1',
    tscKnowledge: "Understanding of the software development lifecycle and CI/CD pipelines.",
    tscAbilities: "Ability to use basic version control and understand deployment automation.",
    courseRunId: '1133673',
    trainer: 'John Smith',
    trainingHours: 24,
    assessmentHours: 8,
    difficulty: 'Intermediate',
    modeOfLearning: [ModeOfLearning.Virtual],
    courseType: CourseType.IBF,
    enrollmentStatus: 'not-enrolled',
    status: 'Published',
    courseFee: 850,
    taxPercent: 9,
    isWsqFunded: true,
    isSkillsFutureEligible: true,
    isPseaEligible: false,
    isMcesEligible: true,
    isIbfFunded: true,
    isUtapEligible: false,
    startDate: getPastDate(20),
    endDate: getPastDate(15),
    classStatus: ClassStatus.Confirmed,
    paymentStatus: PaymentStatus.Paid,
    assessments: [
      { id: 'a12', title: 'Practical Exam', category: AssessmentCategory.PracticalExam, status: 'Published' },
    ],
    topics: [],
    learners: [
      { name: 'Ivan Rodriguez', progressPercent: 100, quizScore: 91, tel: '97890123', email: 'ivan@example.com', company: 'Web Weavers', paymentStatus: PaymentStatus.Paid, assessmentGrades: [{assessmentId: 'a12', status: 'C'}], submissions: [], grantId: 'GID-008A', grantStatus: TpgStatus.Success, claimStatus: TpgStatus.Success, claimId: 'CID-009A', gender: Gender.Male, dob: '1980-12-01', courseSponsorship: CourseSponsorship.EmployerSponsored, paymentMode: PaymentMode.CompanySponsorship, ethnicity: Ethnicity.Indian, nationality: Nationality.SingaporePR, fees: { totalCourseFee: 850, grantAmount: 400, discount: 0, skillsFutureCreditClaim: 0, cashPayment: 526.5, invoiceNumber: 'INV-2024-0018', receiptNumber: 'REC-2024-0018' } },
    ],
  },
];

// Master list of all unique learners across all courses
export const ALL_MOCK_LEARNERS: LearnerProgress[] = Array.from(
    new Map(
        MOCK_COURSES.flatMap(course => course.learners || []).map(learner => [learner.email, learner])
    ).values()
);

export const MOCK_CALENDAR_EVENTS: CalendarEvent[] = [
    { id: 1, title: 'React Quiz 1', date: '2024-08-15', type: 'quiz' },
    { id: 2, title: 'Live Q&A: Advanced TypeScript', date: '2024-08-20', type: 'lecture' },
    { id: 3, title: 'Final Project Submission', date: '2024-08-30', type: 'assignment' },
    { id: 4, title: 'Unlocking ITIL Success Expert Insights', date: getFutureDate(8), type: 'event', speaker: 'Mahesh Deosthale', eventType: 'Master Class' },
    { id: 5, title: 'Scaling Lean Agile Across Hardware', date: getFutureDate(13), type: 'event', speaker: 'Oskar Kawecki', eventType: 'Master Class' },
    { id: 6, title: 'Meet Us At the SAFe Summit 2025', date: getFutureDate(24), type: 'event', speaker: 'Lindy Quick', eventType: 'Summit' },
    { id: 7, title: 'Unlocking Career Growth with Agile', date: getFutureDate(46), type: 'event', speaker: 'Tertiary LMS Expert', eventType: 'Master Class' },
];

export const MOCK_GRANT_APPLICATIONS: GrantApplication[] = [
  {
    id: 'grant1',
    courseId: 'ai301',
    courseTitle: 'Generative AI Fundamentals',
    trainer: 'Alex Ray',
    reason: 'Requesting funding for advanced API access for student projects.',
    status: 'Pending',
  },
  {
    id: 'grant2',
    courseId: 'ts201',
    courseTitle: 'Advanced TypeScript',
    trainer: 'John Smith',
    reason: 'Application for new video recording equipment.',
    status: 'Approved',
  },
  {
    id: 'grant3',
    courseId: 'react101',
    courseTitle: 'React for Beginners',
    trainer: 'Jane Doe',
    reason: 'Request for premium course hosting features.',
    status: 'Rejected',
  },
];

export const SKILLS_FUTURE_INDUSTRIES = [
    'Advanced Manufacturing', 'Aerospace', 'Air Transport', 'Biopharmaceuticals Manufacturing', 
    'Built Environment', 'Bus', 'Design', 'Early Childhood', 'Electronics', 'Energy and Power', 
    'Environmental Services', 'Financial Services', 'Food Manufacturing', 'Food Services', 'Healthcare', 
    'Hotel and Accommodation Services', 'Human Resource', 'Infocomm Technology', 'Intellectual Property', 
    'Land Transport', 'Landscape', 'Legal', 'Logistics', 'Marine and Offshore', 'Media', 'MICE', 
    'Precision Engineering', 'Private Education', 'Process Construction and Maintenance', 'Public Transport (Rail)', 
    'Retail', 'Sea Transport', 'Security', 'Social Service', 'Tourism', 'Training and Adult Education', 
    'Waste Management', 'Water', 'Wholesale Trade'
];

export const MOCK_LEARNER_PROFILE: LearnerProfile = {
    name: 'Alice Johnson',
    tel: '91234567',
    email: 'alice@example.com',
    nric: 'S1234567A',
    gender: Gender.Female,
    company: 'Tech Solutions',
    employmentStatus: EmploymentStatus.Employed,
    profilePictureUrl: 'https://i.pravatar.cc/150?img=1',
    loginId: 'learner@example.com',
    nationality: Nationality.Singaporean,
    courseSponsorship: CourseSponsorship.EmployerSponsored,
    invoiceUrl: '/mock-invoice.pdf',
    receiptUrl: '/mock-receipt.pdf',
    ethnicity: Ethnicity.Chinese,
    dob: '1995-05-20',
    proFormaInvoiceUrl: '/mock-pro-forma-invoice.pdf',
};

export const MOCK_TRAINERS: TrainerProfile[] = [
  {
    name: 'John Smith',
    tel: '98765432',
    email: 'john.smith@example.com',
    gender: Gender.Male,
    trainerType: TrainerType.ACLP,
    status: TrainerStatus.Active,
    areasOfExpertise: [
        'Infocomm Technology',
        'Advanced Manufacturing',
        'Financial Services',
    ],
    profilePictureUrl: 'https://i.pravatar.cc/150?img=68',
    loginId: 'trainer@example.com',
    qualifications: [Qualification.ACLP, Qualification.DACE],
    education: [Education.Master],
    workExperience: [
        { id: 'we_trainer_1', jobTitle: 'Senior Corporate Trainer', company: 'FutureSkills Academy', startDate: '2018-01', endDate: 'Present', description: 'Delivered training on emerging technologies to Fortune 500 companies.' },
        { id: 'we_trainer_2', jobTitle: 'Technical Instructor', company: 'Code Institute', startDate: '2015-06', endDate: '2017-12', description: 'Taught full-stack web development bootcamps.' },
    ],
    linkedinUrl: 'https://linkedin.com/in/johnsmith-mock',
    cvUrl: '/mock-cv-john.pdf',
    certifications: [
        { id: 'cert1', name: 'Certified Agile Professional', url: '/mock-cert-agile.pdf' },
        { id: 'cert2', name: 'Advanced DACE Certification', url: '/mock-cert-dace.pdf' },
    ],
  },
  {
    name: 'Jane Doe',
    tel: '91112222',
    email: 'jane.doe@example.com',
    gender: Gender.Female,
    trainerType: TrainerType.DACE,
    status: TrainerStatus.Active,
    areasOfExpertise: [
        'Project Management',
        'Design',
        'Media',
    ],
    profilePictureUrl: 'https://i.pravatar.cc/150?img=47',
    loginId: 'trainer2@example.com',
    qualifications: [Qualification.DACE],
    education: [Education.Degree],
    workExperience: [
        { id: 'we_trainer_3', jobTitle: 'Agile Coach', company: 'Innovate Inc.', startDate: '2019-03', endDate: 'Present', description: 'Coached teams on Agile and Scrum methodologies.' },
    ],
    linkedinUrl: 'https://linkedin.com/in/janedoe-mock',
    cvUrl: undefined,
    certifications: [],
  },
  {
    name: 'Alex Ray',
    tel: '93334444',
    email: 'alex.ray@example.com',
    gender: Gender.Male,
    trainerType: TrainerType.NonACLP,
    status: TrainerStatus.Inactive,
    areasOfExpertise: [
        'Artificial Intelligence',
        'Data Science',
    ],
    profilePictureUrl: 'https://i.pravatar.cc/150?img=32',
    loginId: 'trainer3@example.com',
    qualifications: [],
    education: [Education.PhD],
    workExperience: [
        { id: 'we_trainer_4', jobTitle: 'AI Research Scientist', company: 'GenTech', startDate: '2020-01', endDate: '2023-12', description: 'Published research on generative models.' },
    ],
    linkedinUrl: 'https://linkedin.com/in/alexray-mock',
    cvUrl: '/mock-cv-alex.pdf',
    certifications: [],
  },
];

export const MOCK_DEVELOPER_PROFILE: DeveloperProfile = {
    name: 'Dev User',
    tel: '91112222',
    email: 'dev@example.com',
    profilePictureUrl: 'https://i.pravatar.cc/150?img=5',
    loginId: 'developer@example.com',
    qualifications: [Qualification.ACLP],
    education: [Education.Degree],
    areasOfSpecialty: ['Infocomm Technology', 'Design', 'Media'],
    workExperience: [
        { id: 'we_dev_1', jobTitle: 'Lead Software Engineer', company: 'Tertiary LMS', startDate: '2020-03', endDate: 'Present', description: 'Architect and lead developer for the Tertiary LMS platform.' },
    ],
    cvUrl: '/mock-cv-dev.pdf',
    certifications: [
        { id: 'cert_dev_1', name: 'React Advanced Certification', url: '/mock-cert-react.pdf' }
    ],
    developerType: DeveloperType.DACE,
    gender: Gender.Male,
    linkedinUrl: 'https://linkedin.com/in/devuser-mock',
};

export const MOCK_ADMIN_PROFILE: AdminProfile = {
    name: 'Admin User',
    tel: '93334444',
    email: 'admin@example.com',
    profilePictureUrl: 'https://avatar.iran.liara.run/public/boy?username=adminuser',
    loginId: 'admin@example.com',
};

export const MOCK_TRAINING_PROVIDER_PROFILE: TrainingProviderProfile = {
    companyName: 'Tertiary Training Solutions Pte Ltd',
    companyShortname: 'TTS',
    uen: '202412345A',
    companyAddress: '123 Tech Park, Singapore 123456',
    contactPerson: {
        name: 'Jane Doe',
        email: 'jane.doe@tertiary-training.com',
        tel: '65-61234567',
    },
    apiKeys: {
        openAI: 'sk-********************************',
        gemini: 'AIzaSy***************************',
        deepSeek: 'ds_*******************************',
        groq: 'gsk_*******************************',
        openrouter: 'sk-or-****************************',
        tavily: 'tvly-******************************',
    },
    companyLogoUrl: 'https://placehold.co/150x150/4f46e5/white?text=TTS',
    invoiceTemplateUrl: undefined,
    receiptTemplateUrl: undefined,
    certificateTemplateUrl: undefined,
    proFormaInvoiceTemplateUrl: undefined,
    loginId: 'provider@example.com',
    ssgCertFile: 'cert.pem',
    ssgPrivateKeyFile: 'private.key',
    ssgEncryptionKey: 'enc_***************************',
    adminSettings: {
        autoSendProFormaInvoice: true,
        autoSendConfirmationEmail: true,
        autoSendInvoiceOnGrantSuccess: false,
        autoSendReceiptOnPayment: true,
        autoSendCertificateOnCompletion: true,
        autoSendThankYouEmail: false,
    },
    integrations: {
        syncGoogleCalendar: true,
        syncMicrosoftCalendar: false,
        googleDrive: true,
        microsoftOneDrive: false,
    },
    securitySettings: {
        autoMaskSensitiveData: true,
        autoDeleteAfter6Months: false,
        enableDefaultOtp: true,
        defaultOtp: '123456',
        enableOtpLogin: true,
    },
    gamingSettings: {
        enableLeaderboard: false,
        enablePoints: false,
    },
    colorScheme: {
        primary: '#4f46e5',
    },
    fundingSettings: {
        normalFunding: 50,
        enhancedFunding: 20,
        isGstRegistered: true,
        gstRate: 9,
    },
};

export const MOCK_JOB_POSTINGS: JobPosting[] = [
    {
        id: 'job1',
        title: 'Frontend Developer (React)',
        company: 'Tech Solutions',
        location: 'Singapore',
        salaryMin: 5000,
        salaryMax: 7000,
        area: 'Infocomm Technology',
        description: 'Join our innovative team to build cutting-edge web applications using React and TypeScript. Experience with state management libraries is a plus.',
        url: '#',
    },
    {
        id: 'job2',
        title: 'Data Analyst',
        company: 'Data Dynamics',
        location: 'Singapore (Hybrid)',
        salaryMin: 4500,
        salaryMax: 6500,
        area: 'Financial Services',
        description: 'Analyze large datasets to provide actionable insights for our financial products. Proficiency in SQL and Python is required.',
        url: '#',
    },
    {
        id: 'job3',
        title: 'Cloud Engineer (AWS)',
        company: 'Innovate Inc.',
        location: 'Singapore',
        salaryMin: 6000,
        salaryMax: 8500,
        area: 'Infocomm Technology',
        description: 'Design, deploy, and manage scalable and secure cloud infrastructure on AWS. AWS certification is highly desirable.',
        url: '#',
    },
    {
        id: 'job4',
        title: 'Project Manager (Agile)',
        company: 'Web Weavers',
        location: 'Singapore',
        salaryMin: 7000,
        salaryMax: 9000,
        area: 'Design',
        description: 'Lead our software development teams using Agile methodologies to deliver high-quality products on time and within budget.',
        url: '#',
    },
    {
        id: 'job5',
        title: 'UI/UX Designer',
        company: 'Pixel Perfect',
        location: 'Singapore (Remote)',
        salaryMin: 4000,
        salaryMax: 6000,
        area: 'Design',
        description: 'Create user-centric designs for our mobile and web applications. A strong portfolio is required.',
        url: '#',
    },
    {
        id: 'job6',
        title: 'Cybersecurity Analyst',
        company: 'SecureNet',
        location: 'Singapore',
        salaryMin: 5500,
        salaryMax: 7500,
        area: 'Infocomm Technology',
        description: 'Monitor our networks for security threats, investigate incidents, and implement security measures to protect company data.',
        url: '#',
    }
];
