

import React, { useState, useEffect, useMemo } from 'react';
import { useLms } from '../hooks/useLms';
import { UserRole, LearnerProfile, TrainerProfile, DeveloperProfile, AdminProfile, TrainingProviderProfile, Gender, EmploymentStatus, TrainerType, Nationality, CourseSponsorship, Qualification, Education, WorkExperienceItem, Ethnicity, calculateAgeGroup, DeveloperType } from '../types';
import { SKILLS_FUTURE_INDUSTRIES } from '../constants';
import { Card } from './common/Card';
import { Button } from './common/Button';
import { Icon, IconName } from './common/Icon';
import { generateAvatarImage } from '../services/geminiService';
import Spinner from './common/Spinner';

// --- Reusable & Specific Profile Components ---

const ProfileBioItem: React.FC<{ label: string; value: React.ReactNode }> = ({ label, value }) => (
    <div>
        <p className="text-sm text-subtle">{label}</p>
        <p className="font-semibold text-on-surface break-words">{value}</p>
    </div>
);

// New component for masked fields with admin-only toggle
const MaskedProfileBioItem: React.FC<{ 
    label: string; 
    value: string;
    isVisible: boolean;
    onToggle: () => void;
    isAdmin: boolean;
    maskFn: (val: string) => string;
}> = ({ label, value, isVisible, onToggle, isAdmin, maskFn }) => (
    <div>
        <p className="text-sm text-subtle">{label}</p>
        <div className="flex items-center gap-2">
            <p className="font-semibold text-on-surface break-words">
                {isAdmin && isVisible ? value : maskFn(value)}
            </p>
            {isAdmin && (
                <button onClick={onToggle} className="text-subtle hover:text-primary">
                    <Icon name={isVisible ? IconName.EyeOff : IconName.Eye} className="w-5 h-5" />
                </button>
            )}
        </div>
    </div>
);


const inputClasses = "block w-full px-3 py-2 text-on-surface bg-white border border-gray-300 rounded-md shadow-sm placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-primary focus:border-transparent";

const LoginDetailsCard: React.FC<{ loginId: string }> = ({ loginId }) => {
    const [isPasswordVisible, setIsPasswordVisible] = useState(false);
    const autogeneratedPassword = "Str0ngP@ssw0rd!23"; // Autogenerated strong password

    return (
        <Card className="p-8 mt-8">
            <h2 className="text-xl font-bold mb-4">Login Details</h2>
            <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-x-8 gap-y-4 flex-grow">
                    <div>
                        <p className="text-sm text-subtle">Login ID</p>
                        <p className="font-semibold text-on-surface break-words">{loginId}</p>
                    </div>
                    <div>
                        <p className="text-sm text-subtle">Password</p>
                        <div className="flex items-center gap-2">
                            <p className="font-semibold text-on-surface font-mono tracking-wider">
                                {isPasswordVisible ? autogeneratedPassword : '••••••••••••••••'}
                            </p>
                            <button onClick={() => setIsPasswordVisible(!isPasswordVisible)} className="text-subtle hover:text-primary p-1 rounded-full">
                                <Icon name={isPasswordVisible ? IconName.EyeOff : IconName.Eye} className="w-5 h-5" />
                            </button>
                        </div>
                    </div>
                </div>
                <Button variant="ghost" className="border border-gray-300 mt-4 sm:mt-0 flex-shrink-0">Reset Password</Button>
            </div>
        </Card>
    );
};

const WorkExperienceSection: React.FC<{ experience: WorkExperienceItem[]; isEditing: boolean; onUpdate: (newExp: WorkExperienceItem[]) => void }> = ({ experience, isEditing, onUpdate }) => {
    
    if (isEditing) {
        return (
            <div className="space-y-4">
                {experience.map((item, index) => (
                    <div key={item.id} className="p-4 border rounded-md relative group">
                        <div className="grid grid-cols-2 gap-4">
                            <input type="text" placeholder="Job Title" value={item.jobTitle} onChange={e => onUpdate(experience.map(i => i.id === item.id ? { ...i, jobTitle: e.target.value } : i))} className={`${inputClasses} col-span-2`} />
                            <input type="text" placeholder="Company" value={item.company} onChange={e => onUpdate(experience.map(i => i.id === item.id ? { ...i, company: e.target.value } : i))} className={inputClasses} />
                            <input type="text" placeholder="Start Date (YYYY-MM)" value={item.startDate} onChange={e => onUpdate(experience.map(i => i.id === item.id ? { ...i, startDate: e.target.value } : i))} className={inputClasses} />
                             <input type="text" placeholder="End Date (YYYY-MM or Present)" value={item.endDate} onChange={e => onUpdate(experience.map(i => i.id === item.id ? { ...i, endDate: e.target.value } : i))} className={inputClasses} />
                             <textarea placeholder="Description" value={item.description} onChange={e => onUpdate(experience.map(i => i.id === item.id ? { ...i, description: e.target.value } : i))} className={`${inputClasses} col-span-2 h-20`}></textarea>
                        </div>
                        <button onClick={() => onUpdate(experience.filter(i => i.id !== item.id))} className="absolute top-2 right-2 p-1.5 text-gray-400 hover:text-red-500 hover:bg-red-100 rounded-full opacity-0 group-hover:opacity-100 transition-opacity">
                            <Icon name={IconName.Delete} className="w-4 h-4" />
                        </button>
                    </div>
                ))}
                <Button variant="ghost" size="sm" onClick={() => onUpdate([...experience, { id: `we_${Date.now()}`, jobTitle: '', company: '', startDate: '', endDate: 'Present', description: '' }])}>
                    + Add Experience
                </Button>
            </div>
        );
    }

    return (
        <div className="space-y-4">
            {experience.map(item => (
                <div key={item.id} className="p-4 border border-gray-200 rounded-md">
                    <h4 className="font-bold">{item.jobTitle}</h4>
                    <p className="text-subtle">{item.company} | {item.startDate} - {item.endDate}</p>
                    <p className="text-sm mt-1">{item.description}</p>
                </div>
            ))}
            {experience.length === 0 && <p className="text-subtle">No work experience listed.</p>}
        </div>
    );
};

const MultiSelectCheckboxes: React.FC<{
    options: string[];
    selected: string[];
    onChange: (e: React.ChangeEvent<HTMLInputElement>) => void;
    isEditing: boolean;
    color: 'primary' | 'secondary'
}> = ({ options, selected, onChange, isEditing, color }) => {
    
    const colorClasses = {
        primary: { ring: 'focus:ring-primary', text: 'text-primary' },
        secondary: { ring: 'focus:ring-secondary', text: 'text-secondary' },
    }

    if (isEditing) {
        return (
            <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-4 max-h-60 overflow-y-auto p-4 border rounded-md">
                {options.map(option => (
                    <div key={option} className="flex items-center">
                        <input
                            type="checkbox"
                            id={`option-${option}`}
                            value={option}
                            checked={selected.includes(option)}
                            onChange={onChange}
                            className={`h-4 w-4 ${colorClasses[color].text} ${colorClasses[color].ring} border-gray-300 rounded`}
                        />
                        <label htmlFor={`option-${option}`} className="ml-2 text-sm text-gray-900">{option}</label>
                    </div>
                ))}
            </div>
        );
    }
    
    return (
         <div className="flex flex-wrap gap-2">
            {selected.map(item => (
                <span key={item} className={`text-sm font-medium px-3 py-1.5 rounded-full ${color === 'primary' ? 'bg-indigo-100 text-indigo-800' : 'bg-green-100 text-green-800'}`}>
                    {item}
                </span>
            ))}
             {selected.length === 0 && <p className="text-subtle text-sm">Not specified.</p>}
        </div>
    )
}

const DocumentSection: React.FC<{
    title: string;
    cvUrl?: string;
    certifications?: { id: string; name: string; url: string; }[];
    isEditing: boolean;
    onUpdateCv: (file: File) => void;
    onAddCertification: (name: string, file: File) => void;
    onRemoveCertification: (id: string) => void;
}> = ({ title, cvUrl, certifications, isEditing, onUpdateCv, onAddCertification, onRemoveCertification }) => {
    
    const [newCertName, setNewCertName] = useState('');

    const handleAddCert = (file: File | null) => {
        if (file && newCertName) {
            onAddCertification(newCertName, file);
            setNewCertName('');
            (document.getElementById('cert-upload') as HTMLInputElement).value = ''; // Reset file input
        } else {
            alert("Please provide a name for the certification.");
        }
    };

    if (isEditing) {
        return (
            <section>
                <h2 className="text-xl font-bold mb-4">{title}</h2>
                <div className="space-y-4">
                    {/* CV Upload */}
                    <div>
                        <label className="block text-sm font-medium text-gray-700 mb-1">Curriculum Vitae (CV)</label>
                        <div className="flex items-center gap-2 p-2 bg-gray-50 rounded-md border">
                            <Icon name={IconName.FilePdf} className="w-5 h-5 text-gray-500" />
                            <span className="text-sm text-subtle flex-grow">{cvUrl ? cvUrl.split('/').pop() : 'No CV uploaded.'}</span>
                            <Button variant="ghost" size="sm" onClick={() => document.getElementById('cv-upload')?.click()}>
                                <Icon name={IconName.Upload} className="w-4 h-4 mr-1"/> Upload New
                            </Button>
                            <input type="file" id="cv-upload" className="hidden" onChange={(e) => e.target.files && onUpdateCv(e.target.files[0])} accept=".pdf,.doc,.docx"/>
                        </div>
                    </div>
                    {/* Certifications List (Editable) */}
                    <div>
                        <label className="block text-sm font-medium text-gray-700 mb-1">Certifications</label>
                        <div className="space-y-2">
                             {(certifications || []).map(cert => (
                                <div key={cert.id} className="flex items-center gap-2 p-2 bg-gray-50 rounded-md border">
                                    <Icon name={IconName.FilePdf} className="w-5 h-5 text-gray-500" />
                                    <span className="text-sm text-on-surface flex-grow">{cert.name}</span>
                                    <button onClick={() => onRemoveCertification(cert.id)} className="p-1.5 text-gray-400 hover:text-red-500 hover:bg-red-100 rounded-full">
                                        <Icon name={IconName.Delete} className="w-4 h-4" />
                                    </button>
                                </div>
                            ))}
                             <div className="flex items-center gap-2 p-2 bg-gray-100 rounded-md border border-dashed">
                                <input type="text" placeholder="New Certification Name" value={newCertName} onChange={e => setNewCertName(e.target.value)} className={`${inputClasses} !py-1.5 !text-sm`} />
                                <Button variant="ghost" size="sm" onClick={() => document.getElementById('cert-upload')?.click()}>
                                    <Icon name={IconName.Upload} className="w-4 h-4 mr-1"/> Attach File
                                </Button>
                                <input type="file" id="cert-upload" className="hidden" onChange={(e) => e.target.files && handleAddCert(e.target.files[0])} accept=".pdf,.jpg,.png"/>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        );
    }

    return (
        <section>
            <h2 className="text-xl font-bold mb-4">{title}</h2>
            <div className="space-y-4">
                {cvUrl && (
                     <a href={cvUrl} target="_blank" rel="noopener noreferrer" className="flex items-center gap-3 p-3 bg-gray-50 rounded-md border hover:bg-gray-100 transition-colors">
                        <Icon name={IconName.FilePdf} className="w-6 h-6 text-red-600 flex-shrink-0" />
                        <div>
                            <p className="font-semibold text-on-surface">Curriculum Vitae</p>
                            <p className="text-xs text-subtle">Click to view/download</p>
                        </div>
                    </a>
                )}
                 {(certifications && certifications.length > 0) && (
                    <div className="space-y-2">
                         {certifications.map(cert => (
                            <a key={cert.id} href={cert.url} target="_blank" rel="noopener noreferrer" className="flex items-center gap-3 p-3 bg-gray-50 rounded-md border hover:bg-gray-100 transition-colors">
                                <Icon name={IconName.FilePdf} className="w-6 h-6 text-red-600 flex-shrink-0" />
                                <div>
                                    <p className="font-semibold text-on-surface">{cert.name}</p>
                                    <p className="text-xs text-subtle">Click to view/download</p>
                                </div>
                            </a>
                        ))}
                    </div>
                )}
                 {!cvUrl && (!certifications || certifications.length === 0) && <p className="text-subtle text-sm">No documents uploaded.</p>}
            </div>
        </section>
    );
};

const LearnerProfileCard: React.FC<{ profile: LearnerProfile }> = ({ profile }) => {
    const [isEditing, setIsEditing] = useState(false);
    const [formData, setFormData] = useState(profile);
    const [showNric, setShowNric] = useState(false);
    const [showDob, setShowDob] = useState(false);
    const [isGeneratingAvatar, setIsGeneratingAvatar] = useState(false);
    const { role, updateLearnerProfile, courses } = useLms();
    const isAdmin = role === UserRole.Admin;

    useEffect(() => {
        setFormData(profile);
    }, [profile]);

    const completedCoursesWithCerts = useMemo(() => {
        return courses
            .map(course => {
                const learnerProgress = course.learners?.find(l => l.email === profile.email);
                if (!learnerProgress || !course.certificateUrl) {
                    return null;
                }

                const hasAssessments = course.assessments && course.assessments.length > 0;
                if (!hasAssessments) {
                    return null;
                }
                
                const allAssessmentsGraded = learnerProgress.assessmentGrades.length >= course.assessments.length;
                if (!allAssessmentsGraded) {
                    return null;
                }

                const allCompetent = learnerProgress.assessmentGrades.every(g => g.status === 'C');

                if (allCompetent) {
                    return {
                        id: course.id,
                        title: course.title,
                        url: course.certificateUrl,
                    };
                }
                return null;
            })
            .filter((c): c is { id: string; title: string; url: string; } => c !== null);
    }, [courses, profile.email]);

    const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement>) => {
        setFormData({ ...formData, [e.target.name]: e.target.value });
    };

    const handlePhotoChange = (e: React.ChangeEvent<HTMLInputElement>) => {
        if (e.target.files && e.target.files[0]) {
            const file = e.target.files[0];
            const reader = new FileReader();
            reader.onloadend = () => {
                setFormData(prev => ({ ...prev, profilePictureUrl: reader.result as string }));
            };
            reader.readAsDataURL(file);
        }
    };
    
    const handleGenerateAvatar = async () => {
        setIsGeneratingAvatar(true);
        try {
            const newAvatarUrl = await generateAvatarImage(formData.name);
            if (newAvatarUrl) {
                setFormData(prev => ({ ...prev, profilePictureUrl: newAvatarUrl }));
            } else {
                alert("Failed to generate avatar. Please try again.");
            }
        } catch (error) {
            console.error("Avatar generation failed:", error);
            alert("An error occurred while generating the avatar.");
        } finally {
            setIsGeneratingAvatar(false);
        }
    };

    const handleSave = () => {
        updateLearnerProfile(formData);
        setIsEditing(false);
    };
    
    return (
    <>
        <Card className="p-8">
            <div className="flex flex-col sm:flex-row items-center gap-6">
                 <div className="flex-shrink-0 text-center">
                    <div className="relative group w-24 h-24">
                        <img src={formData.profilePictureUrl} alt={formData.name} className="w-24 h-24 rounded-full object-cover ring-4 ring-primary/20" />
                         {isGeneratingAvatar && (
                            <div className="absolute inset-0 bg-black/70 flex items-center justify-center rounded-full">
                                <Spinner />
                            </div>
                        )}
                        {isEditing && !isGeneratingAvatar && (
                            <>
                                <input type="file" id="photo-upload-learner" className="hidden" accept="image/*" onChange={handlePhotoChange} />
                                <label htmlFor="photo-upload-learner" className="absolute inset-0 bg-black/50 flex items-center justify-center text-white rounded-full cursor-pointer opacity-0 group-hover:opacity-100 transition-opacity">
                                    <Icon name={IconName.Upload} className="w-8 h-8"/>
                                </label>
                            </>
                        )}
                    </div>
                     {isEditing && (
                         <Button
                            variant="ghost"
                            size="sm"
                            className="mt-2"
                            onClick={handleGenerateAvatar}
                            disabled={isGeneratingAvatar}
                         >
                             {isGeneratingAvatar ? <Spinner size="sm" /> : 'Generate Avatar'}
                         </Button>
                    )}
                </div>
                <div className="text-center sm:text-left flex-grow">
                    <h1 className="text-2xl font-bold">{isEditing ? 'Editing Profile' : formData.name}</h1>
                    <p className="text-subtle">Learner Profile</p>
                </div>
                {isEditing ? (
                    <div className="flex items-center gap-2">
                        <Button variant="ghost" onClick={() => { setIsEditing(false); setFormData(profile); }}>Cancel</Button>
                        <Button onClick={handleSave}>Save Changes</Button>
                    </div>
                ) : (
                    <Button onClick={() => setIsEditing(true)}>Edit Profile</Button>
                )}
            </div>
            <div className="border-t my-6"></div>
            <h2 className="text-xl font-bold mb-4">Bio Data</h2>
            
            {isEditing ? (
                <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
                    <div><label className="text-sm font-medium">Name</label><input type="text" name="name" value={formData.name} onChange={handleChange} className={inputClasses} /></div>
                    <div><label className="text-sm font-medium">Telephone</label><input type="tel" name="tel" value={formData.tel} onChange={handleChange} className={inputClasses} /></div>
                    <div><label className="text-sm font-medium">Email</label><input type="email" name="email" value={formData.email} onChange={handleChange} className={inputClasses} /></div>
                    <div><label className="text-sm font-medium">Date of Birth</label><input type="date" name="dob" value={formData.dob} onChange={handleChange} className={inputClasses} /></div>
                    <div><label className="text-sm font-medium">NRIC</label><input type="text" name="nric" value={formData.nric || ''} onChange={handleChange} className={inputClasses} /></div>
                    <div><label className="text-sm font-medium">Race</label><select name="ethnicity" value={formData.ethnicity} onChange={handleChange} className={inputClasses}>{Object.values(Ethnicity).map(e => <option key={e} value={e}>{e}</option>)}</select></div>
                    <div><label className="text-sm font-medium">Gender</label><select name="gender" value={formData.gender} onChange={handleChange} className={inputClasses}>{Object.values(Gender).map(g => <option key={g} value={g}>{g}</option>)}</select></div>
                    <div><label className="text-sm font-medium">Company</label><input type="text" name="company" value={formData.company} onChange={handleChange} className={inputClasses} /></div>
                    <div><label className="text-sm font-medium">Employment Status</label><select name="employmentStatus" value={formData.employmentStatus} onChange={handleChange} className={inputClasses}>{Object.values(EmploymentStatus).map(s => <option key={s} value={s}>{s}</option>)}</select></div>
                    <div><label className="text-sm font-medium">Nationality</label><select name="nationality" value={formData.nationality} onChange={handleChange} className={inputClasses}>{Object.values(Nationality).map(n => <option key={n} value={n}>{n}</option>)}</select></div>
                </div>
            ) : (
                <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
                    <ProfileBioItem label="Name" value={formData.name} />
                    <ProfileBioItem label="Telephone" value={formData.tel} />
                    <ProfileBioItem label="Email" value={formData.email} />
                    <MaskedProfileBioItem
                        label="Date of Birth"
                        value={new Date(formData.dob).toLocaleDateString('en-GB')}
                        isVisible={showDob}
                        onToggle={() => setShowDob(!showDob)}
                        isAdmin={isAdmin}
                        maskFn={() => 'XX/XX/XXXX'}
                    />
                    <MaskedProfileBioItem
                        label="NRIC"
                        value={formData.nric || 'N/A'}
                        isVisible={showNric}
                        onToggle={() => setShowNric(!showNric)}
                        isAdmin={isAdmin}
                        maskFn={(val) => val && val !== 'N/A' ? `${val.slice(0, 1)}****${val.slice(-4)}` : 'N/A'}
                    />
                    <ProfileBioItem label="Race" value={formData.ethnicity} />
                    <ProfileBioItem label="Age Group" value={calculateAgeGroup(formData.dob)} />
                    <ProfileBioItem label="Gender" value={formData.gender} />
                    <ProfileBioItem label="Company" value={formData.company} />
                    <ProfileBioItem label="Employment Status" value={formData.employmentStatus} />
                    <ProfileBioItem label="Nationality" value={formData.nationality} />
                </div>
            )}
            
            {!isEditing && (
                <>
                    <div className="border-t my-6"></div>
                    <h2 className="text-xl font-bold mb-4">Billing Documents</h2>
                    <div className="space-y-4">
                        {formData.proFormaInvoiceUrl && (
                             <div className="flex justify-between items-center p-3 bg-gray-50 rounded-md border">
                                <div>
                                    <p className="font-semibold">Pro Forma Invoice</p>
                                    <p className="text-xs text-subtle">Pro forma invoice for your enrollment.</p>
                                </div>
                                <Button 
                                    variant="ghost" 
                                    size="sm" 
                                    onClick={() => window.open(formData.proFormaInvoiceUrl, '_blank')}
                                >
                                    Download
                                </Button>
                            </div>
                        )}
                        <div className="flex justify-between items-center p-3 bg-gray-50 rounded-md border">
                            <div>
                                <p className="font-semibold">Course Invoice</p>
                                <p className="text-xs text-subtle">Invoice for your course enrollment.</p>
                            </div>
                            <Button 
                                variant="ghost" 
                                size="sm" 
                                disabled={!formData.invoiceUrl}
                                onClick={() => formData.invoiceUrl && window.open(formData.invoiceUrl, '_blank')}
                            >
                                Download
                            </Button>
                        </div>
                        <div className="flex justify-between items-center p-3 bg-gray-50 rounded-md border">
                            <div>
                                <p className="font-semibold">Payment Receipt</p>
                                <p className="text-xs text-subtle">Receipt for your payment.</p>
                            </div>
                            <Button 
                                variant="ghost" 
                                size="sm" 
                                disabled={!formData.receiptUrl}
                                onClick={() => formData.receiptUrl && window.open(formData.receiptUrl, '_blank')}
                            >
                                Download
                            </Button>
                        </div>
                    </div>
                </>
            )}

            {!isEditing && completedCoursesWithCerts.length > 0 && (
                <>
                    <div className="border-t my-6"></div>
                    <h2 className="text-xl font-bold mb-4">Certificates of Completion</h2>
                    <div className="space-y-4">
                        {completedCoursesWithCerts.map(cert => (
                            <div key={cert.id} className="flex justify-between items-center p-3 bg-gray-50 rounded-md border">
                                <div className="flex items-center gap-3">
                                    <Icon name={IconName.Certificate} className="w-6 h-6 text-green-500 flex-shrink-0" />
                                    <div>
                                        <p className="font-semibold">{cert.title}</p>
                                        <p className="text-xs text-subtle">Certificate of Completion</p>
                                    </div>
                                </div>
                                <a href={cert.url} target="_blank" rel="noopener noreferrer">
                                    <Button 
                                        variant="ghost" 
                                        size="sm" 
                                    >
                                        Download
                                    </Button>
                                </a>
                            </div>
                        ))}
                    </div>
                </>
            )}
        </Card>
        <LoginDetailsCard loginId={formData.loginId} />
    </>
    );
};

const TrainerProfileCard: React.FC<{ profile: TrainerProfile }> = ({ profile }) => {
    const [isEditing, setIsEditing] = useState(false);
    const [formData, setFormData] = useState(profile);
    const [isGeneratingAvatar, setIsGeneratingAvatar] = useState(false);
    const { updateTrainerProfile } = useLms();

    useEffect(() => {
        setFormData(profile);
    }, [profile]);

    const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement>) => {
        setFormData({ ...formData, [e.target.name]: e.target.value });
    };

    const handleMultiSelectChange = (field: 'areasOfExpertise' | 'qualifications' | 'education') => (e: React.ChangeEvent<HTMLInputElement>) => {
        const { value, checked } = e.target;
        setFormData(prev => {
            const currentValues = prev[field] || [];
            if (checked) {
                return { ...prev, [field]: [...new Set([...currentValues, value])] };
            } else {
                return { ...prev, [field]: currentValues.filter(item => item !== value) };
            }
        });
    };
    
    const handleWorkExperienceUpdate = (newExp: WorkExperienceItem[]) => {
        setFormData(prev => ({...prev, workExperience: newExp}));
    }

    const handlePhotoChange = (e: React.ChangeEvent<HTMLInputElement>) => {
        if (e.target.files && e.target.files[0]) {
            const file = e.target.files[0];
            const reader = new FileReader();
            reader.onloadend = () => {
                setFormData(prev => ({ ...prev, profilePictureUrl: reader.result as string }));
            };
            reader.readAsDataURL(file);
        }
    };

    const handleGenerateAvatar = async () => {
        setIsGeneratingAvatar(true);
        try {
            const newAvatarUrl = await generateAvatarImage(formData.name);
            if (newAvatarUrl) {
                setFormData(prev => ({ ...prev, profilePictureUrl: newAvatarUrl }));
            } else {
                alert("Failed to generate avatar. Please try again.");
            }
        } catch (error) {
            console.error("Avatar generation failed:", error);
            alert("An error occurred while generating the avatar.");
        } finally {
            setIsGeneratingAvatar(false);
        }
    };

    const handleCvUpdate = (file: File) => {
        // In a real app, you would upload the file and get a URL
        setFormData(prev => ({...prev, cvUrl: file.name}));
    };

    const handleAddCertification = (name: string, file: File) => {
        // In a real app, you would upload the file and get a URL
        const newCert = { id: `cert_${Date.now()}`, name, url: file.name };
        setFormData(prev => ({ ...prev, certifications: [...(prev.certifications || []), newCert] }));
    };

    const handleRemoveCertification = (id: string) => {
        setFormData(prev => ({ ...prev, certifications: (prev.certifications || []).filter(c => c.id !== id) }));
    };


    const handleSave = () => {
        updateTrainerProfile(formData);
        setIsEditing(false);
    };

    return (
     <>
        <Card className="p-8">
            <div className="flex flex-col sm:flex-row items-center gap-6">
                 <div className="flex-shrink-0 text-center">
                    <div className="relative group w-24 h-24">
                        <img src={formData.profilePictureUrl} alt={formData.name} className="w-24 h-24 rounded-full object-cover ring-4 ring-secondary/20" />
                        {isGeneratingAvatar && (
                            <div className="absolute inset-0 bg-black/70 flex items-center justify-center rounded-full">
                                <Spinner />
                            </div>
                        )}
                        {isEditing && !isGeneratingAvatar && (
                            <>
                                <input type="file" id="photo-upload-trainer" className="hidden" accept="image/*" onChange={handlePhotoChange} />
                                <label htmlFor="photo-upload-trainer" className="absolute inset-0 bg-black/50 flex items-center justify-center text-white rounded-full cursor-pointer opacity-0 group-hover:opacity-100 transition-opacity">
                                    <Icon name={IconName.Upload} className="w-8 h-8"/>
                                </label>
                            </>
                        )}
                    </div>
                     {isEditing && (
                         <Button
                            variant="ghost"
                            size="sm"
                            className="mt-2"
                            onClick={handleGenerateAvatar}
                            disabled={isGeneratingAvatar}
                         >
                             {isGeneratingAvatar ? <Spinner size="sm" /> : 'Generate Avatar'}
                         </Button>
                    )}
                </div>
                <div className="text-center sm:text-left flex-grow">
                    <h1 className="text-2xl font-bold">{isEditing ? 'Editing Profile' : formData.name}</h1>
                    <p className="text-subtle">Trainer Profile</p>
                </div>
                 {isEditing ? (
                    <div className="flex items-center gap-2">
                        <Button variant="ghost" onClick={() => { setIsEditing(false); setFormData(profile); }}>Cancel</Button>
                        <Button variant="secondary" onClick={handleSave}>Save Changes</Button>
                    </div>
                ) : (
                    <Button variant="secondary" onClick={() => setIsEditing(true)}>Edit Profile</Button>
                )}
            </div>
            <div className="border-t my-6"></div>
            
            <div className="space-y-6">
                <section>
                    <h2 className="text-xl font-bold mb-4">Bio Data</h2>
                    {isEditing ? (
                        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6 mb-6">
                            <div><label className="text-sm font-medium">Name</label><input type="text" name="name" value={formData.name} onChange={handleChange} className={inputClasses} /></div>
                            <div><label className="text-sm font-medium">Telephone</label><input type="tel" name="tel" value={formData.tel} onChange={handleChange} className={inputClasses} /></div>
                            <div><label className="text-sm font-medium">Email</label><input type="email" name="email" value={formData.email} onChange={handleChange} className={inputClasses} /></div>
                            <div><label className="text-sm font-medium">Gender</label><select name="gender" value={formData.gender} onChange={handleChange} className={inputClasses}>{Object.values(Gender).map(g => <option key={g} value={g}>{g}</option>)}</select></div>
                            <div><label className="text-sm font-medium">Trainer Type</label><select name="trainerType" value={formData.trainerType} onChange={handleChange} className={inputClasses}>{Object.values(TrainerType).map(t => <option key={t} value={t}>{t}</option>)}</select></div>
                            <div><label className="text-sm font-medium">LinkedIn Profile URL</label><input type="url" name="linkedinUrl" value={formData.linkedinUrl || ''} onChange={handleChange} className={inputClasses} placeholder="https://linkedin.com/in/..."/></div>
                        </div>
                    ) : (
                        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6 mb-6">
                            <ProfileBioItem label="Name" value={formData.name} />
                            <ProfileBioItem label="Telephone" value={formData.tel} />
                            <ProfileBioItem label="Email" value={formData.email} />
                            <ProfileBioItem label="Gender" value={formData.gender} />
                            <ProfileBioItem label="Trainer Type" value={formData.trainerType} />
                            {formData.linkedinUrl && (
                                <ProfileBioItem 
                                    label="LinkedIn Profile" 
                                    value={
                                        <a href={formData.linkedinUrl} target="_blank" rel="noopener noreferrer" className="text-primary hover:underline flex items-center gap-1.5">
                                            <Icon name={IconName.LinkedIn} className="w-4 h-4" />
                                            View Profile
                                        </a>
                                    } 
                                />
                            )}
                        </div>
                    )}
                </section>
                
                <DocumentSection
                    title="CV & Certifications"
                    cvUrl={formData.cvUrl}
                    certifications={formData.certifications}
                    isEditing={isEditing}
                    onUpdateCv={handleCvUpdate}
                    onAddCertification={handleAddCertification}
                    onRemoveCertification={handleRemoveCertification}
                />

                <section><h2 className="text-xl font-bold mb-4">Qualifications</h2><MultiSelectCheckboxes options={Object.values(Qualification)} selected={formData.qualifications} onChange={handleMultiSelectChange('qualifications')} isEditing={isEditing} color="secondary" /></section>
                <section><h2 className="text-xl font-bold mb-4">Education</h2><MultiSelectCheckboxes options={Object.values(Education)} selected={formData.education} onChange={handleMultiSelectChange('education')} isEditing={isEditing} color="secondary" /></section>
                <section><h2 className="text-xl font-bold mb-4">Area of Expertise</h2><MultiSelectCheckboxes options={SKILLS_FUTURE_INDUSTRIES} selected={formData.areasOfExpertise} onChange={handleMultiSelectChange('areasOfExpertise')} isEditing={isEditing} color="secondary" /></section>
                <section><h2 className="text-xl font-bold mb-4">Work Experience</h2><WorkExperienceSection experience={formData.workExperience} isEditing={isEditing} onUpdate={handleWorkExperienceUpdate} /></section>
            </div>
        </Card>
        <LoginDetailsCard loginId={formData.loginId} />
    </>
    );
};

const DeveloperProfileCard: React.FC<{ profile: DeveloperProfile }> = ({ profile }) => {
    const [isEditing, setIsEditing] = useState(false);
    const [formData, setFormData] = useState(profile);
    const [isGeneratingAvatar, setIsGeneratingAvatar] = useState(false);
    const { updateDeveloperProfile } = useLms();
    
    useEffect(() => {
        setFormData(profile);
    }, [profile]);

    const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement>) => {
        setFormData({ ...formData, [e.target.name]: e.target.value });
    };

    const handleMultiSelectChange = (field: 'qualifications' | 'education' | 'areasOfSpecialty') => (e: React.ChangeEvent<HTMLInputElement>) => {
        const { value, checked } = e.target;
        setFormData(prev => {
            const currentValues = prev[field] || [];
            if (checked) {
                return { ...prev, [field]: [...new Set([...currentValues, value])] };
            } else {
                return { ...prev, [field]: currentValues.filter(item => item !== value) };
            }
        });
    };

    const handleWorkExperienceUpdate = (newExp: WorkExperienceItem[]) => {
        setFormData(prev => ({ ...prev, workExperience: newExp }));
    };

    const handlePhotoChange = (e: React.ChangeEvent<HTMLInputElement>) => {
        if (e.target.files && e.target.files[0]) {
            const file = e.target.files[0];
            const reader = new FileReader();
            reader.onloadend = () => {
                setFormData(prev => ({ ...prev, profilePictureUrl: reader.result as string }));
            };
            reader.readAsDataURL(file);
        }
    };

     const handleGenerateAvatar = async () => {
        setIsGeneratingAvatar(true);
        try {
            const newAvatarUrl = await generateAvatarImage(formData.name);
            if (newAvatarUrl) {
                setFormData(prev => ({ ...prev, profilePictureUrl: newAvatarUrl }));
            } else {
                alert("Failed to generate avatar. Please try again.");
            }
        } catch (error) {
            console.error("Avatar generation failed:", error);
            alert("An error occurred while generating the avatar.");
        } finally {
            setIsGeneratingAvatar(false);
        }
    };

    const handleCvUpdate = (file: File) => {
        setFormData(prev => ({...prev, cvUrl: file.name}));
    };

    const handleAddCertification = (name: string, file: File) => {
        const newCert = { id: `cert_${Date.now()}`, name, url: file.name };
        setFormData(prev => ({ ...prev, certifications: [...(prev.certifications || []), newCert] }));
    };

    const handleRemoveCertification = (id: string) => {
        setFormData(prev => ({ ...prev, certifications: (prev.certifications || []).filter(c => c.id !== id) }));
    };

    const handleSave = () => {
        updateDeveloperProfile(formData);
        setIsEditing(false);
    };

    return (
    <>
        <Card className="p-8">
            <div className="flex flex-col sm:flex-row items-center gap-6">
                 <div className="flex-shrink-0 text-center">
                    <div className="relative group w-24 h-24">
                        <img src={formData.profilePictureUrl} alt={formData.name} className="w-24 h-24 rounded-full object-cover ring-4 ring-purple-500/20" />
                        {isGeneratingAvatar && (
                            <div className="absolute inset-0 bg-black/70 flex items-center justify-center rounded-full">
                                <Spinner />
                            </div>
                        )}
                        {isEditing && !isGeneratingAvatar && (
                            <>
                                <input type="file" id="photo-upload-dev" className="hidden" accept="image/*" onChange={handlePhotoChange} />
                                <label htmlFor="photo-upload-dev" className="absolute inset-0 bg-black/50 flex items-center justify-center text-white rounded-full cursor-pointer opacity-0 group-hover:opacity-100 transition-opacity">
                                    <Icon name={IconName.Upload} className="w-8 h-8"/>
                                </label>
                            </>
                        )}
                    </div>
                     {isEditing && (
                         <Button
                            variant="ghost"
                            size="sm"
                            className="mt-2"
                            onClick={handleGenerateAvatar}
                            disabled={isGeneratingAvatar}
                         >
                             {isGeneratingAvatar ? <Spinner size="sm" /> : 'Generate Avatar'}
                         </Button>
                    )}
                </div>
                <div className="text-center sm:text-left flex-grow">
                    <h1 className="text-2xl font-bold">{isEditing ? 'Editing Profile' : formData.name}</h1>
                    <p className="text-subtle">Developer Profile</p>
                </div>
                 {isEditing ? (
                    <div className="flex items-center gap-2">
                        <Button variant="ghost" onClick={() => { setIsEditing(false); setFormData(profile); }}>Cancel</Button>
                        <Button onClick={handleSave}>Save Changes</Button>
                    </div>
                ) : (
                    <Button onClick={() => setIsEditing(true)}>Edit Profile</Button>
                )}
            </div>
            <div className="border-t my-6"></div>
            
            <div className="space-y-6">
                 <section>
                    <h2 className="text-xl font-bold mb-4">Bio Data</h2>
                    {isEditing ? (
                         <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6 mb-6">
                            <div><label className="text-sm font-medium">Name</label><input type="text" name="name" value={formData.name} onChange={handleChange} className={inputClasses} /></div>
                            <div><label className="text-sm font-medium">Telephone</label><input type="tel" name="tel" value={formData.tel} onChange={handleChange} className={inputClasses} /></div>
                            <div><label className="text-sm font-medium">Email</label><input type="email" name="email" value={formData.email} onChange={handleChange} className={inputClasses} /></div>
                            <div><label className="text-sm font-medium">Developer Type</label><select name="developerType" value={formData.developerType} onChange={handleChange} className={inputClasses}>{Object.values(DeveloperType).map(t => <option key={t} value={t}>{t}</option>)}</select></div>
                            <div><label className="text-sm font-medium">Gender</label><select name="gender" value={formData.gender} onChange={handleChange} className={inputClasses}>{Object.values(Gender).map(g => <option key={g} value={g}>{g}</option>)}</select></div>
                            <div><label className="text-sm font-medium">LinkedIn Profile URL</label><input type="url" name="linkedinUrl" value={formData.linkedinUrl || ''} onChange={handleChange} className={inputClasses} placeholder="https://linkedin.com/in/..."/></div>
                        </div>
                    ) : (
                        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6 mb-6">
                            <ProfileBioItem label="Name" value={formData.name} />
                            <ProfileBioItem label="Telephone" value={formData.tel} />
                            <ProfileBioItem label="Email" value={formData.email} />
                            <ProfileBioItem label="Developer Type" value={formData.developerType} />
                            <ProfileBioItem label="Gender" value={formData.gender} />
                            {formData.linkedinUrl && (
                                <ProfileBioItem 
                                    label="LinkedIn Profile" 
                                    value={
                                        <a href={formData.linkedinUrl} target="_blank" rel="noopener noreferrer" className="text-primary hover:underline flex items-center gap-1.5">
                                            <Icon name={IconName.LinkedIn} className="w-4 h-4" />
                                            View Profile
                                        </a>
                                    } 
                                />
                            )}
                        </div>
                    )}
                 </section>

                <DocumentSection
                    title="CV & Certifications"
                    cvUrl={formData.cvUrl}
                    certifications={formData.certifications}
                    isEditing={isEditing}
                    onUpdateCv={handleCvUpdate}
                    onAddCertification={handleAddCertification}
                    onRemoveCertification={handleRemoveCertification}
                />

                <section><h2 className="text-xl font-bold mb-4">Qualifications</h2><MultiSelectCheckboxes options={Object.values(Qualification)} selected={formData.qualifications} onChange={handleMultiSelectChange('qualifications')} isEditing={isEditing} color="primary" /></section>
                <section><h2 className="text-xl font-bold mb-4">Education</h2><MultiSelectCheckboxes options={Object.values(Education)} selected={formData.education} onChange={handleMultiSelectChange('education')} isEditing={isEditing} color="primary" /></section>
                <section><h2 className="text-xl font-bold mb-4">Area of Specialty</h2><MultiSelectCheckboxes options={SKILLS_FUTURE_INDUSTRIES} selected={formData.areasOfSpecialty} onChange={handleMultiSelectChange('areasOfSpecialty')} isEditing={isEditing} color="primary" /></section>
                <section><h2 className="text-xl font-bold mb-4">Work Experience</h2><WorkExperienceSection experience={formData.workExperience} isEditing={isEditing} onUpdate={handleWorkExperienceUpdate} /></section>
            </div>
        </Card>
        <LoginDetailsCard loginId={formData.loginId} />
    </>
    );
};

const AdminProfileCard: React.FC<{ profile: AdminProfile }> = ({ profile }) => {
    const [isEditing, setIsEditing] = useState(false);
    const [formData, setFormData] = useState(profile);
    const [isGeneratingAvatar, setIsGeneratingAvatar] = useState(false);
    const { updateAdminProfile } = useLms();

    useEffect(() => {
        setFormData(profile);
    }, [profile]);

    const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
        setFormData({ ...formData, [e.target.name]: e.target.value });
    };

    const handlePhotoChange = (e: React.ChangeEvent<HTMLInputElement>) => {
        if (e.target.files && e.target.files[0]) {
            const file = e.target.files[0];
            const reader = new FileReader();
            reader.onloadend = () => {
                setFormData(prev => ({ ...prev, profilePictureUrl: reader.result as string }));
            };
            reader.readAsDataURL(file);
        }
    };

    const handleGenerateAvatar = async () => {
        setIsGeneratingAvatar(true);
        try {
            const newAvatarUrl = await generateAvatarImage(formData.name);
            if (newAvatarUrl) {
                setFormData(prev => ({ ...prev, profilePictureUrl: newAvatarUrl }));
            } else {
                alert("Failed to generate avatar. Please try again.");
            }
        } catch (error) {
            console.error("Avatar generation failed:", error);
            alert("An error occurred while generating the avatar.");
        } finally {
            setIsGeneratingAvatar(false);
        }
    };

    const handleSave = () => {
        updateAdminProfile(formData);
        setIsEditing(false);
    };

     return (
     <>
        <Card className="p-8">
             <div className="flex flex-col sm:flex-row items-center gap-6">
                 <div className="flex-shrink-0 text-center">
                    <div className="relative group w-24 h-24">
                        <img src={formData.profilePictureUrl} alt={formData.name} className="w-24 h-24 rounded-full object-cover ring-4 ring-indigo-500/20" />
                        {isGeneratingAvatar && (
                            <div className="absolute inset-0 bg-black/70 flex items-center justify-center rounded-full">
                                <Spinner />
                            </div>
                        )}
                        {isEditing && !isGeneratingAvatar && (
                            <>
                                <input type="file" id="photo-upload-admin" className="hidden" accept="image/*" onChange={handlePhotoChange} />
                                <label htmlFor="photo-upload-admin" className="absolute inset-0 bg-black/50 flex items-center justify-center text-white rounded-full cursor-pointer opacity-0 group-hover:opacity-100 transition-opacity">
                                    <Icon name={IconName.Upload} className="w-8 h-8"/>
                                </label>
                            </>
                        )}
                    </div>
                     {isEditing && (
                         <Button
                            variant="ghost"
                            size="sm"
                            className="mt-2"
                            onClick={handleGenerateAvatar}
                            disabled={isGeneratingAvatar}
                         >
                             {isGeneratingAvatar ? <Spinner size="sm" /> : 'Generate Avatar'}
                         </Button>
                    )}
                </div>
                <div className="text-center sm:text-left flex-grow">
                    <h1 className="text-2xl font-bold">{isEditing ? 'Editing Profile' : formData.name}</h1>
                    <p className="text-subtle">Admin Profile</p>
                </div>
                 {isEditing ? (
                    <div className="flex items-center gap-2">
                        <Button variant="ghost" onClick={() => { setIsEditing(false); setFormData(profile); }}>Cancel</Button>
                        <Button onClick={handleSave}>Save Changes</Button>
                    </div>
                ) : (
                    <Button onClick={() => setIsEditing(true)}>Edit Profile</Button>
                )}
            </div>
            <div className="border-t my-6"></div>
             <h2 className="text-xl font-bold mb-4">Bio Data</h2>
              {isEditing ? (
                <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
                    <div><label className="text-sm font-medium">Name</label><input type="text" name="name" value={formData.name} onChange={handleChange} className={inputClasses} /></div>
                    <div><label className="text-sm font-medium">Telephone</label><input type="tel" name="tel" value={formData.tel} onChange={handleChange} className={inputClasses} /></div>
                    <div><label className="text-sm font-medium">Email</label><input type="email" name="email" value={formData.email} onChange={handleChange} className={inputClasses} /></div>
                </div>
            ) : (
                <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
                    <ProfileBioItem label="Name" value={formData.name} />
                    <ProfileBioItem label="Telephone" value={formData.tel} />
                    <ProfileBioItem label="Email" value={formData.email} />
                </div>
            )}
        </Card>
        <LoginDetailsCard loginId={formData.loginId} />
    </>
    );
};

const TrainingProviderProfileCard: React.FC<{ profile: TrainingProviderProfile }> = ({ profile }) => {
    const [isEditing, setIsEditing] = useState(false);
    const [formData, setFormData] = useState(profile);
    const [newApiKey, setNewApiKey] = useState({ name: '', value: '' });
    const [isGeneratingLogo, setIsGeneratingLogo] = useState(false);
    const { updateTrainingProviderProfile } = useLms();

    const adminSettingLabels: { [key: string]: string } = {
        autoSendProFormaInvoice: "Auto Send Pro Forma Invoice Upon Course Confirmation",
        autoSendConfirmationEmail: "Auto Send Confirmation Email Upon Course Confirmation",
        autoSendInvoiceOnGrantSuccess: "Auto Send Invoice Upon Successful Grant Application",
        autoSendReceiptOnPayment: "Auto Send Receipt Upon Payment Received",
        autoSendCertificateOnCompletion: "Auto Send Certificate On Achievement Upon Class Completed",
        autoSendThankYouEmail: "Auto Send Thank You Email Upon Class Completed",
    };

    useEffect(() => {
        setFormData(profile);
    }, [profile]);

    const handleInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
        const { name, value } = e.target;
        setFormData(prev => ({ ...prev, [name]: value }));
    };
    
    const handleContactChange = (e: React.ChangeEvent<HTMLInputElement>) => {
        const { name, value } = e.target;
        setFormData(prev => ({ ...prev, contactPerson: { ...prev.contactPerson, [name]: value } }));
    };

    const handleToggleChange = (section: 'adminSettings' | 'securitySettings' | 'integrations' | 'gamingSettings' | 'fundingSettings', key: string) => {
        setFormData(prev => ({
            ...prev,
            [section]: {
                ...prev[section],
                [key]: !(prev[section] as any)[key],
            }
        }));
    };
    
    const handleFundingChange = (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement>) => {
        const { name, value } = e.target;
        const parsedValue = (name === 'normalFunding' || name === 'enhancedFunding' || name === 'gstRate') ? parseFloat(value) : value;

        setFormData(prev => ({
            ...prev,
            fundingSettings: {
                ...prev.fundingSettings,
                [name]: parsedValue,
            }
        }));
    };

    const handleAddApiKey = () => {
        if (newApiKey.name.trim() && newApiKey.value.trim()) {
            setFormData(prev => ({ ...prev, apiKeys: { ...prev.apiKeys, [newApiKey.name]: newApiKey.value } }));
            setNewApiKey({ name: '', value: '' });
        }
    };
    
    const handleLogoChange = (e: React.ChangeEvent<HTMLInputElement>) => {
        if (e.target.files && e.target.files[0]) {
            const file = e.target.files[0];
            const reader = new FileReader();
            reader.onloadend = () => {
                setFormData(prev => ({ ...prev, companyLogoUrl: reader.result as string }));
            };
            reader.readAsDataURL(file);
        }
    };

     const handleGenerateLogo = async () => {
        setIsGeneratingLogo(true);
        try {
            const newLogoUrl = await generateAvatarImage(formData.companyName); // Reusing avatar generator for simplicity
            if (newLogoUrl) {
                setFormData(prev => ({ ...prev, companyLogoUrl: newLogoUrl }));
            } else {
                alert("Failed to generate logo. Please try again.");
            }
        } catch (error) {
            console.error("Logo generation failed:", error);
            alert("An error occurred while generating the logo.");
        } finally {
            setIsGeneratingLogo(false);
        }
    };
    
    const handleColorChange = (e: React.ChangeEvent<HTMLInputElement>) => {
        const { name, value } = e.target;
        setFormData(prev => ({ ...prev, colorScheme: { ...prev.colorScheme, [name]: value }}));
    };

    const handleTemplateUpload = (e: React.ChangeEvent<HTMLInputElement>, field: 'invoiceTemplateUrl' | 'receiptTemplateUrl' | 'certificateTemplateUrl' | 'proFormaInvoiceTemplateUrl') => {
        if (e.target.files && e.target.files[0]) {
            // In a real app, you would upload the file and get a URL.
            // For this mock, we'll just store the file name to simulate it.
            const mockUrl = `/mock-data/templates/${e.target.files[0].name}`;
            setFormData(prev => ({ ...prev, [field]: mockUrl }));
        }
    };

    const handleSave = () => {
        updateTrainingProviderProfile(formData);
        setIsEditing(false);
    };

    return (
    <>
        <Card className="p-8">
            <div className="flex flex-col sm:flex-row items-center gap-6">
                <div className="flex-shrink-0 text-center">
                    <div className="relative group w-24 h-24">
                        <img src={formData.companyLogoUrl} alt={formData.companyName} className="w-24 h-24 rounded-md object-cover ring-4 ring-blue-500/20" />
                        {isGeneratingLogo && (
                            <div className="absolute inset-0 bg-black/70 flex items-center justify-center rounded-md">
                                <Spinner />
                            </div>
                        )}
                         {isEditing && !isGeneratingLogo && (
                            <>
                                <input
                                    type="file"
                                    id="logo-upload"
                                    className="hidden"
                                    accept="image/*"
                                    onChange={handleLogoChange}
                                />
                                <label
                                    htmlFor="logo-upload"
                                    className="absolute inset-0 bg-black/60 flex items-center justify-center text-white rounded-md cursor-pointer opacity-0 group-hover:opacity-100 transition-opacity"
                                >
                                    <Icon name={IconName.Upload} className="w-8 h-8" />
                                </label>
                            </>
                        )}
                    </div>
                    {isEditing && (
                        <Button
                            variant="ghost"
                            size="sm"
                            className="mt-2"
                            onClick={handleGenerateLogo}
                            disabled={isGeneratingLogo}
                        >
                            {isGeneratingLogo ? <Spinner size="sm"/> : 'Generate Logo'}
                        </Button>
                    )}
                </div>

                <div className="text-center sm:text-left flex-grow">
                    <h1 className="text-2xl font-bold">{isEditing ? 'Editing Profile' : formData.companyName}</h1>
                    <p className="text-subtle">Training Provider Profile</p>
                </div>
                 {isEditing ? (
                    <div className="flex items-center gap-2">
                        <Button variant="ghost" onClick={() => { setIsEditing(false); setFormData(profile); }}>Cancel</Button>
                        <Button onClick={handleSave}>Save Changes</Button>
                    </div>
                ) : (
                    <Button onClick={() => setIsEditing(true)}>Edit Profile</Button>
                )}
            </div>
            
            <div className="border-t my-6"></div>
            <h2 className="text-xl font-bold mb-4">Company Details</h2>
             {isEditing ? (
                 <div className="grid grid-cols-1 sm:grid-cols-2 gap-6 mb-6">
                    <div><label className="text-sm font-medium">Company Name</label><input type="text" name="companyName" value={formData.companyName} onChange={handleInputChange} className={inputClasses} /></div>
                    <div><label className="text-sm font-medium">Company Shortname</label><input type="text" name="companyShortname" value={formData.companyShortname} onChange={handleInputChange} className={inputClasses} /></div>
                    <div><label className="text-sm font-medium">UEN</label><input type="text" name="uen" value={formData.uen} onChange={handleInputChange} className={inputClasses} /></div>
                    <div className="sm:col-span-2"><label className="text-sm font-medium">Address</label><input type="text" name="companyAddress" value={formData.companyAddress} onChange={handleInputChange} className={inputClasses} /></div>
                </div>
            ) : (
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-6 mb-6">
                    <ProfileBioItem label="Company Name" value={formData.companyName} />
                    <ProfileBioItem label="Company Shortname" value={formData.companyShortname} />
                    <ProfileBioItem label="UEN" value={formData.uen} />
                    <ProfileBioItem label="Address" value={formData.companyAddress} />
                </div>
            )}
            
            <div className="border-t my-6"></div>
            <h2 className="text-xl font-bold mb-4">Contact Person</h2>
             {isEditing ? (
                <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6 mb-6">
                     <div><label className="text-sm font-medium">Name</label><input type="text" name="name" value={formData.contactPerson.name} onChange={handleContactChange} className={inputClasses} /></div>
                     <div><label className="text-sm font-medium">Email</label><input type="email" name="email" value={formData.contactPerson.email} onChange={handleContactChange} className={inputClasses} /></div>
                     <div><label className="text-sm font-medium">Telephone</label><input type="tel" name="tel" value={formData.contactPerson.tel} onChange={handleContactChange} className={inputClasses} /></div>
                </div>
            ) : (
                <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6 mb-6">
                    <ProfileBioItem label="Name" value={formData.contactPerson.name} />
                    <ProfileBioItem label="Email" value={formData.contactPerson.email} />
                    <ProfileBioItem label="Telephone" value={formData.contactPerson.tel} />
                </div>
            )}

            <div className="border-t my-6"></div>
            <h2 className="text-xl font-bold mb-4">API Keys</h2>
            <div className="space-y-3 mb-4">
                {Object.entries(formData.apiKeys).map(([key, value]) => (
                    <ProfileBioItem key={key} label={key.charAt(0).toUpperCase() + key.slice(1).replace(/([A-Z])/g, ' $1').trim()} value={value.slice(0, 8) + '...'} />
                ))}
            </div>
            {isEditing && (
                 <div className="flex flex-col sm:flex-row items-center gap-2 p-3 bg-gray-50 rounded-md border">
                    <input type="text" placeholder="API Key Name" value={newApiKey.name} onChange={e => setNewApiKey({...newApiKey, name: e.target.value})} className={`${inputClasses} flex-1`} />
                    <input type="text" placeholder="API Key Value" value={newApiKey.value} onChange={e => setNewApiKey({...newApiKey, value: e.target.value})} className={`${inputClasses} flex-1`} />
                    <Button size="sm" onClick={handleAddApiKey}>Add Key</Button>
                </div>
            )}

            <div className="border-t my-6"></div>
            <h2 className="text-xl font-bold mb-4">Document Templates</h2>
            <div className="space-y-4">
                 <div className="flex justify-between items-center p-3 bg-gray-50 rounded-md border">
                    <div><p className="font-semibold">Pro Forma Invoice Template</p><p className="text-xs text-subtle">{formData.proFormaInvoiceTemplateUrl ? formData.proFormaInvoiceTemplateUrl.split('/').pop() : 'No template uploaded.'}</p></div>
                    {isEditing && (
                        <>
                            <Button variant="ghost" size="sm" onClick={() => document.getElementById('pro-forma-invoice-upload')?.click()}>Upload</Button>
                            <input type="file" id="pro-forma-invoice-upload" className="hidden" onChange={(e) => handleTemplateUpload(e, 'proFormaInvoiceTemplateUrl')} accept=".doc,.docx,.pdf" />
                        </>
                    )}
                </div>
                <div className="flex justify-between items-center p-3 bg-gray-50 rounded-md border">
                    <div><p className="font-semibold">Invoice Template</p><p className="text-xs text-subtle">{formData.invoiceTemplateUrl ? formData.invoiceTemplateUrl.split('/').pop() : 'No template uploaded.'}</p></div>
                    {isEditing && (
                        <>
                            <Button variant="ghost" size="sm" onClick={() => document.getElementById('invoice-upload')?.click()}>Upload</Button>
                            <input type="file" id="invoice-upload" className="hidden" onChange={(e) => handleTemplateUpload(e, 'invoiceTemplateUrl')} accept=".doc,.docx,.pdf" />
                        </>
                    )}
                </div>
                 <div className="flex justify-between items-center p-3 bg-gray-50 rounded-md border">
                    <div><p className="font-semibold">Receipt Template</p><p className="text-xs text-subtle">{formData.receiptTemplateUrl ? formData.receiptTemplateUrl.split('/').pop() : 'No template uploaded.'}</p></div>
                    {isEditing && (
                        <>
                            <Button variant="ghost" size="sm" onClick={() => document.getElementById('receipt-upload')?.click()}>Upload</Button>
                            <input type="file" id="receipt-upload" className="hidden" onChange={(e) => handleTemplateUpload(e, 'receiptTemplateUrl')} accept=".doc,.docx,.pdf" />
                        </>
                    )}
                </div>
                <div className="flex justify-between items-center p-3 bg-gray-50 rounded-md border">
                    <div><p className="font-semibold">Certificate Template</p><p className="text-xs text-subtle">{formData.certificateTemplateUrl ? formData.certificateTemplateUrl.split('/').pop() : 'No template uploaded.'}</p></div>
                    {isEditing && (
                         <>
                            <Button variant="ghost" size="sm" onClick={() => document.getElementById('certificate-upload')?.click()}>Upload</Button>
                            <input type="file" id="certificate-upload" className="hidden" onChange={(e) => handleTemplateUpload(e, 'certificateTemplateUrl')} accept=".doc,.docx,.pdf" />
                        </>
                    )}
                </div>
            </div>

            <div className="border-t my-6"></div>
            <h2 className="text-xl font-bold mb-4">SSG Developer Authorisation</h2>
             {isEditing ? (
                 <div className="space-y-4">
                    <div>
                        <label className="block text-sm font-medium text-gray-700 mb-1">Self Signing Cert File</label>
                        <div className="flex items-center gap-2 p-2 bg-gray-50 rounded-md border">
                            <span className="text-sm text-subtle flex-grow">{formData.ssgCertFile || 'No file uploaded.'}</span>
                            <Button variant="ghost" size="sm" onClick={() => alert('File upload simulated.')}>Upload File</Button>
                        </div>
                    </div>
                     <div>
                        <label className="block text-sm font-medium text-gray-700 mb-1">Private Key File</label>
                        <div className="flex items-center gap-2 p-2 bg-gray-50 rounded-md border">
                            <span className="text-sm text-subtle flex-grow">{formData.ssgPrivateKeyFile || 'No file uploaded.'}</span>
                            <Button variant="ghost" size="sm" onClick={() => alert('File upload simulated.')}>Upload File</Button>
                        </div>
                    </div>
                     <div>
                        <label htmlFor="ssgEncryptionKey" className="block text-sm font-medium text-gray-700 mb-1">Encryption Key</label>
                        <input 
                            type="text"
                            id="ssgEncryptionKey"
                            name="ssgEncryptionKey" 
                            value={formData.ssgEncryptionKey || ''} 
                            onChange={handleInputChange} 
                            className={inputClasses} 
                            placeholder="Enter your encryption key"
                        />
                    </div>
                </div>
            ) : (
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">
                    <ProfileBioItem label="Self Signing Cert File" value={formData.ssgCertFile || 'Not Uploaded'} />
                    <ProfileBioItem label="Private Key File" value={formData.ssgPrivateKeyFile || 'Not Uploaded'} />
                    <ProfileBioItem label="Encryption Key" value={formData.ssgEncryptionKey ? '••••••••••••••••' : 'Not Set'} />
                </div>
            )}

            <div className="border-t my-6"></div>
            <h2 className="text-xl font-bold mb-4">Integrations</h2>
            <div className="space-y-4">
                <div className="flex justify-between items-center p-3 bg-gray-50 rounded-md border">
                    <p className="font-semibold text-sm">Sync with Google Calendar</p>
                    {isEditing ? (
                            <button onClick={() => handleToggleChange('integrations', 'syncGoogleCalendar')} className={`relative inline-flex h-6 w-11 items-center rounded-full transition-colors ${formData.integrations.syncGoogleCalendar ? 'bg-primary' : 'bg-gray-200'}`}>
                            <span className={`inline-block h-4 w-4 transform rounded-full bg-white transition-transform ${formData.integrations.syncGoogleCalendar ? 'translate-x-6' : 'translate-x-1'}`} />
                        </button>
                    ) : (
                            <span className={`px-3 py-1 text-xs font-bold rounded-full ${formData.integrations.syncGoogleCalendar ? 'bg-green-100 text-green-800' : 'bg-red-100 text-red-800'}`}>
                            {formData.integrations.syncGoogleCalendar ? 'Enabled' : 'Disabled'}
                        </span>
                    )}
                </div>
                <div className="flex justify-between items-center p-3 bg-gray-50 rounded-md border">
                    <p className="font-semibold text-sm">Sync with Microsoft Calendar</p>
                    {isEditing ? (
                        <button onClick={() => handleToggleChange('integrations', 'syncMicrosoftCalendar')} className={`relative inline-flex h-6 w-11 items-center rounded-full transition-colors ${formData.integrations.syncMicrosoftCalendar ? 'bg-primary' : 'bg-gray-200'}`}>
                            <span className={`inline-block h-4 w-4 transform rounded-full bg-white transition-transform ${formData.integrations.syncMicrosoftCalendar ? 'translate-x-6' : 'translate-x-1'}`} />
                        </button>
                    ) : (
                        <span className={`px-3 py-1 text-xs font-bold rounded-full ${formData.integrations.syncMicrosoftCalendar ? 'bg-green-100 text-green-800' : 'bg-red-100 text-red-800'}`}>
                            {formData.integrations.syncMicrosoftCalendar ? 'Enabled' : 'Disabled'}
                        </span>
                    )}
                </div>
                 <div className="flex justify-between items-center p-3 bg-gray-50 rounded-md border">
                    <p className="font-semibold text-sm">Google Drive</p>
                    {isEditing ? (
                        <button onClick={() => handleToggleChange('integrations', 'googleDrive')} className={`relative inline-flex h-6 w-11 items-center rounded-full transition-colors ${formData.integrations.googleDrive ? 'bg-primary' : 'bg-gray-200'}`}>
                            <span className={`inline-block h-4 w-4 transform rounded-full bg-white transition-transform ${formData.integrations.googleDrive ? 'translate-x-6' : 'translate-x-1'}`} />
                        </button>
                    ) : (
                        <span className={`px-3 py-1 text-xs font-bold rounded-full ${formData.integrations.googleDrive ? 'bg-green-100 text-green-800' : 'bg-red-100 text-red-800'}`}>
                            {formData.integrations.googleDrive ? 'Enabled' : 'Disabled'}
                        </span>
                    )}
                </div>
                 <div className="flex justify-between items-center p-3 bg-gray-50 rounded-md border">
                    <p className="font-semibold text-sm">Microsoft One Drive</p>
                    {isEditing ? (
                        <button onClick={() => handleToggleChange('integrations', 'microsoftOneDrive')} className={`relative inline-flex h-6 w-11 items-center rounded-full transition-colors ${formData.integrations.microsoftOneDrive ? 'bg-primary' : 'bg-gray-200'}`}>
                            <span className={`inline-block h-4 w-4 transform rounded-full bg-white transition-transform ${formData.integrations.microsoftOneDrive ? 'translate-x-6' : 'translate-x-1'}`} />
                        </button>
                    ) : (
                        <span className={`px-3 py-1 text-xs font-bold rounded-full ${formData.integrations.microsoftOneDrive ? 'bg-green-100 text-green-800' : 'bg-red-100 text-red-800'}`}>
                            {formData.integrations.microsoftOneDrive ? 'Enabled' : 'Disabled'}
                        </span>
                    )}
                </div>
            </div>

            <div className="border-t my-6"></div>
            <h2 className="text-xl font-bold mb-4">Admin Setting</h2>
            <div className="space-y-4">
                {Object.entries(formData.adminSettings).map(([key, value]) => (
                    <div key={key} className="flex justify-between items-center p-3 bg-gray-50 rounded-md border">
                        <p className="font-semibold text-sm">{adminSettingLabels[key] || key.replace(/([A-Z])/g, ' $1').replace(/^./, str => str.toUpperCase())}</p>
                        {isEditing ? (
                             <button onClick={() => handleToggleChange('adminSettings', key)} className={`relative inline-flex h-6 w-11 items-center rounded-full transition-colors ${value ? 'bg-primary' : 'bg-gray-200'}`}>
                                <span className={`inline-block h-4 w-4 transform rounded-full bg-white transition-transform ${value ? 'translate-x-6' : 'translate-x-1'}`} />
                            </button>
                        ) : (
                             <span className={`px-3 py-1 text-xs font-bold rounded-full ${value ? 'bg-green-100 text-green-800' : 'bg-red-100 text-red-800'}`}>
                                {value ? 'Enabled' : 'Disabled'}
                            </span>
                        )}
                    </div>
                ))}
            </div>

            <div className="border-t my-6"></div>
            <h2 className="text-xl font-bold mb-4">Security</h2>
            <div className="space-y-4">
                <div className="flex justify-between items-center p-3 bg-gray-50 rounded-md border">
                    <p className="font-semibold text-sm">Auto Mask Sensitive Data</p>
                    {isEditing ? (
                        <button onClick={() => handleToggleChange('securitySettings', 'autoMaskSensitiveData')} className={`relative inline-flex h-6 w-11 items-center rounded-full transition-colors ${formData.securitySettings.autoMaskSensitiveData ? 'bg-primary' : 'bg-gray-200'}`}>
                            <span className={`inline-block h-4 w-4 transform rounded-full bg-white transition-transform ${formData.securitySettings.autoMaskSensitiveData ? 'translate-x-6' : 'translate-x-1'}`} />
                        </button>
                    ) : (
                        <span className={`px-3 py-1 text-xs font-bold rounded-full ${formData.securitySettings.autoMaskSensitiveData ? 'bg-green-100 text-green-800' : 'bg-red-100 text-red-800'}`}>
                            {formData.securitySettings.autoMaskSensitiveData ? 'Enabled' : 'Disabled'}
                        </span>
                    )}
                </div>
                <div className="flex justify-between items-center p-3 bg-gray-50 rounded-md border">
                    <p className="font-semibold text-sm">Auto Delete After 6 Months</p>
                    {isEditing ? (
                        <button onClick={() => handleToggleChange('securitySettings', 'autoDeleteAfter6Months')} className={`relative inline-flex h-6 w-11 items-center rounded-full transition-colors ${formData.securitySettings.autoDeleteAfter6Months ? 'bg-primary' : 'bg-gray-200'}`}>
                            <span className={`inline-block h-4 w-4 transform rounded-full bg-white transition-transform ${formData.securitySettings.autoDeleteAfter6Months ? 'translate-x-6' : 'translate-x-1'}`} />
                        </button>
                    ) : (
                        <span className={`px-3 py-1 text-xs font-bold rounded-full ${formData.securitySettings.autoDeleteAfter6Months ? 'bg-green-100 text-green-800' : 'bg-red-100 text-red-800'}`}>
                            {formData.securitySettings.autoDeleteAfter6Months ? 'Enabled' : 'Disabled'}
                        </span>
                    )}
                </div>
                <div className="flex justify-between items-center p-3 bg-gray-50 rounded-md border">
                    <p className="font-semibold text-sm">Enable OTP Login</p>
                    {isEditing ? (
                        <button onClick={() => handleToggleChange('securitySettings', 'enableOtpLogin')} className={`relative inline-flex h-6 w-11 items-center rounded-full transition-colors ${formData.securitySettings.enableOtpLogin ? 'bg-primary' : 'bg-gray-200'}`}>
                            <span className={`inline-block h-4 w-4 transform rounded-full bg-white transition-transform ${formData.securitySettings.enableOtpLogin ? 'translate-x-6' : 'translate-x-1'}`} />
                        </button>
                    ) : (
                        <span className={`px-3 py-1 text-xs font-bold rounded-full ${formData.securitySettings.enableOtpLogin ? 'bg-green-100 text-green-800' : 'bg-red-100 text-red-800'}`}>
                            {formData.securitySettings.enableOtpLogin ? 'Enabled' : 'Disabled'}
                        </span>
                    )}
                </div>
                {formData.securitySettings.enableOtpLogin && (
                    <>
                        <div className="flex justify-between items-center p-3 bg-gray-50 rounded-md border">
                            <p className="font-semibold text-sm">Enable Default OTP</p>
                            {isEditing ? (
                                <button onClick={() => handleToggleChange('securitySettings', 'enableDefaultOtp')} className={`relative inline-flex h-6 w-11 items-center rounded-full transition-colors ${formData.securitySettings.enableDefaultOtp ? 'bg-primary' : 'bg-gray-200'}`}>
                                    <span className={`inline-block h-4 w-4 transform rounded-full bg-white transition-transform ${formData.securitySettings.enableDefaultOtp ? 'translate-x-6' : 'translate-x-1'}`} />
                                </button>
                            ) : (
                                <span className={`px-3 py-1 text-xs font-bold rounded-full ${formData.securitySettings.enableDefaultOtp ? 'bg-green-100 text-green-800' : 'bg-red-100 text-red-800'}`}>
                                    {formData.securitySettings.enableDefaultOtp ? 'Enabled' : 'Disabled'}
                                </span>
                            )}
                        </div>
                        {formData.securitySettings.enableDefaultOtp && (
                            <div className="flex justify-between items-center p-3 bg-gray-50 rounded-md border">
                                <p className="font-semibold text-sm">Default OTP Value</p>
                                {isEditing ? (
                                    <input
                                        type="text"
                                        value={formData.securitySettings.defaultOtp}
                                        onChange={(e) => {
                                            const { value } = e.target;
                                            setFormData(prev => ({
                                                ...prev,
                                                securitySettings: {
                                                    ...prev.securitySettings,
                                                    defaultOtp: value,
                                                }
                                            }))
                                        }}
                                        className={`${inputClasses} !w-auto max-w-[150px] !py-1 !text-sm`}
                                        placeholder="e.g., 123456"
                                    />
                                ) : (
                                    <p className="font-mono font-semibold">••••••</p>
                                )}
                            </div>
                        )}
                    </>
                )}
            </div>
            
            <div className="border-t my-6"></div>
            <h2 className="text-xl font-bold mb-4">Gamification Settings</h2>
            <div className="space-y-4">
                <div className="flex justify-between items-center p-3 bg-gray-50 rounded-md border">
                    <p className="font-semibold text-sm">Enable Leaderboard</p>
                    {isEditing ? (
                        <button onClick={() => handleToggleChange('gamingSettings', 'enableLeaderboard')} className={`relative inline-flex h-6 w-11 items-center rounded-full transition-colors ${formData.gamingSettings.enableLeaderboard ? 'bg-primary' : 'bg-gray-200'}`}>
                            <span className={`inline-block h-4 w-4 transform rounded-full bg-white transition-transform ${formData.gamingSettings.enableLeaderboard ? 'translate-x-6' : 'translate-x-1'}`} />
                        </button>
                    ) : (
                        <span className={`px-3 py-1 text-xs font-bold rounded-full ${formData.gamingSettings.enableLeaderboard ? 'bg-green-100 text-green-800' : 'bg-red-100 text-red-800'}`}>
                            {formData.gamingSettings.enableLeaderboard ? 'Enabled' : 'Disabled'}
                        </span>
                    )}
                </div>
                <div className="flex justify-between items-center p-3 bg-gray-50 rounded-md border">
                    <p className="font-semibold text-sm">Enable Points System</p>
                    {isEditing ? (
                        <button onClick={() => handleToggleChange('gamingSettings', 'enablePoints')} className={`relative inline-flex h-6 w-11 items-center rounded-full transition-colors ${formData.gamingSettings.enablePoints ? 'bg-primary' : 'bg-gray-200'}`}>
                            <span className={`inline-block h-4 w-4 transform rounded-full bg-white transition-transform ${formData.gamingSettings.enablePoints ? 'translate-x-6' : 'translate-x-1'}`} />
                        </button>
                    ) : (
                        <span className={`px-3 py-1 text-xs font-bold rounded-full ${formData.gamingSettings.enablePoints ? 'bg-green-100 text-green-800' : 'bg-red-100 text-red-800'}`}>
                            {formData.gamingSettings.enablePoints ? 'Enabled' : 'Disabled'}
                        </span>
                    )}
                </div>
            </div>

            <div className="border-t my-6"></div>
            <h2 className="text-xl font-bold mb-4">Funding & Tax Settings</h2>
            {isEditing ? (
                 <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">
                    <div>
                        <label className="block text-sm font-medium text-gray-700 mb-1">Normal Funding Rate</label>
                        <select name="normalFunding" value={formData.fundingSettings.normalFunding} onChange={handleFundingChange} className={inputClasses}>
                            <option value={50}>50%</option>
                            <option value={70}>70%</option>
                        </select>
                    </div>
                    <div>
                        <label className="block text-sm font-medium text-gray-700 mb-1">Enhanced Funding Rate (%)</label>
                        <input type="number" name="enhancedFunding" value={formData.fundingSettings.enhancedFunding} onChange={handleFundingChange} className={inputClasses} />
                    </div>
                    <div>
                        <label className="block text-sm font-medium text-gray-700 mb-1">GST Rate (%)</label>
                        <input type="number" name="gstRate" value={formData.fundingSettings.gstRate} onChange={handleFundingChange} className={inputClasses} />
                    </div>
                    <div className="flex justify-between items-center p-3 bg-gray-50 rounded-md border">
                        <p className="font-semibold text-sm">GST Registered</p>
                         <button onClick={() => handleToggleChange('fundingSettings', 'isGstRegistered')} className={`relative inline-flex h-6 w-11 items-center rounded-full transition-colors ${formData.fundingSettings.isGstRegistered ? 'bg-primary' : 'bg-gray-200'}`}>
                            <span className={`inline-block h-4 w-4 transform rounded-full bg-white transition-transform ${formData.fundingSettings.isGstRegistered ? 'translate-x-6' : 'translate-x-1'}`} />
                        </button>
                    </div>
                 </div>
            ) : (
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">
                    <ProfileBioItem label="Normal Funding Rate" value={`${formData.fundingSettings.normalFunding}%`} />
                    <ProfileBioItem label="Enhanced Funding Rate" value={`${formData.fundingSettings.enhancedFunding}%`} />
                    <ProfileBioItem label="GST Registered" value={formData.fundingSettings.isGstRegistered ? 'Yes' : 'No'} />
                    <ProfileBioItem label="GST Rate" value={`${formData.fundingSettings.gstRate}%`} />
                </div>
            )}
            

            <div className="border-t my-6"></div>
            <h2 className="text-xl font-bold mb-4">Color Scheme</h2>
             <div className="flex justify-between items-center p-3 bg-gray-50 rounded-md border">
                <p className="font-semibold text-sm">Primary Color</p>
                <div className="flex items-center gap-2">
                    {isEditing ? (
                        <input
                            type="color"
                            name="primary"
                            value={formData.colorScheme.primary}
                            onChange={handleColorChange}
                            className="w-10 h-10 rounded-md border border-gray-300 cursor-pointer"
                        />
                    ) : (
                         <div className="w-8 h-8 rounded-md" style={{ backgroundColor: formData.colorScheme.primary }}></div>
                    )}
                    <span className="font-mono text-sm">{formData.colorScheme.primary}</span>
                </div>
            </div>

        </Card>
        <LoginDetailsCard loginId={formData.loginId} />
    </>
    );
};

const ProfileView: React.FC = () => {
    const { role, learnerProfile, trainerProfiles, developerProfile, adminProfile, trainingProviderProfile } = useLms();
    
    const renderProfile = () => {
        switch (role) {
            case UserRole.Learner:
                return <LearnerProfileCard profile={learnerProfile} />;
            case UserRole.Trainer:
                // Find a specific trainer to simulate a logged-in state, using 'John Smith' for consistency.
                const trainerProfile = trainerProfiles.find(t => t.name === 'John Smith') || trainerProfiles[0];
                return <TrainerProfileCard profile={trainerProfile} />;
            case UserRole.Developer:
                return <DeveloperProfileCard profile={developerProfile} />;
            case UserRole.Admin:
                return <AdminProfileCard profile={adminProfile} />;
            case UserRole.TrainingProvider:
                return <TrainingProviderProfileCard profile={trainingProviderProfile} />;
            default:
                return <LearnerProfileCard profile={learnerProfile} />;
        }
    };

    return (
        <div className="max-w-5xl mx-auto">
             {renderProfile()}
        </div>
    );
};

export default ProfileView;
